Repository OffchainLabs/nitro, pull requests merged in 2022-06, with the labels that each got.

#650 Implement new batch fetching scheme for automatic L1 gas pricing
  .github/workflows/docker.yml
  arbnode/api.go
  arbnode/inbox_reader.go
  arbnode/node.go
  arbnode/transaction_streamer.go
  arbos/block_processor.go
  arbos/incomingmessage.go
  arbos/incomingmessage_test.go
  arbos/internal_tx.go
  arbos/tx_processor.go
  arbstate/geth_test.go
  cmd/replay/main.go
  contracts/src/precompiles/ArbosActs.sol
  precompiles/ArbosActs.go
  system_tests/replay_fuzz/replay_fuzz.go
  system_tests/retryable_test.go
  validator/block_validator.go
  validator/challenge_manager.go
  validator/stateless_block_validator.go
Labels: ArbOS

#639 Support complex DAS configurations
  arbnode/inbox_tracker.go
  arbnode/node.go
  arbstate/das_reader.go
  arbstate/inbox.go
  cmd/daserver/daserver.go
  cmd/dasrest/dasrest.go
  cmd/nitro/config_test.go
  cmd/nitro/nitro.go
  cmd/replay/main.go
  das/aggregator.go
  das/aggregator_test.go
  das/archiving_storage_service.go
  das/archiving_storage_service_test.go
  das/bigcache_storage_service.go
  das/cache_storage_to_das_adapter.go
  das/chain_fetch_das.go
  das/das.go
  das/das_test.go
  das/dasrpc/dasRpcClient.go
  das/dasrpc/dasRpcServer.go
  das/dasrpc/rpc_test.go
  das/db_storage_service.go
  das/factory.go
  das/fallback_storage_service.go
  das/lifecycle.go
  das/local_disk_das.go
  das/local_file_storage_service.go
  das/memory_backed_storage_service.go
  das/read_limited.go
  das/reader_aggregator_strategies.go
  das/reader_aggregator_strategies_test.go
  das/redis_storage_service.go
  das/redis_storage_service_test.go
  das/redundant_simple_das_reader.go
  das/redundant_storage_service.go
  das/restful_client.go
  das/restful_server.go
  das/restful_server_test.go
  das/s3_storage_service.go
  das/s3_storage_service_test.go
  das/sign_after_store_das.go
  das/simple_das_reader_aggregator.go
  das/simple_das_reader_aggregator_test.go
  das/storage_service.go
  das/store_signing.go
  das/sync_from_l1_chain.go
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/seqfeed_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
  util/pretty/pretty_printing.go
  util/stopwaiter/stopwaiter.go
  validator/block_validator.go
  validator/challenge_manager.go
  validator/l1_validator.go
  validator/staker.go
  validator/stateless_block_validator.go
Labels: AnyTrust

#643 Downloader for RESTful DAS list
  das/rest_server_list.go
  das/restful_server_list_test.go
Labels: AnyTrust

#660 Update .clabot to add Aman
  .clabot
Labels: cla-signed

#657 Combined rpc rest da server
  arbnode/node.go
  cmd/daserver/daserver.go
  cmd/datool/datool.go
  das/chain_fetch_das.go
  das/dasrpc/dasRpcClient.go
  das/dasrpc/dasRpcServer.go
  das/db_storage_service.go
  das/fallback_storage_service.go
  das/local_file_storage_service.go
  das/restful_client.go
  das/restful_server.go
Labels: AnyTrust, cla-signed

#665 Fix segfault when DAS not enabled
  arbnode/node.go
Labels: cla-signed

#667 Add config for starting eager chain sync for DAS
  arbnode/node.go
  das/das.go
  das/simple_das_reader_aggregator.go
  das/sync_from_l1_chain.go
Labels: AnyTrust, cla-signed

#652 Expiration rest rpc api
  arbstate/das_reader.go
  cmd/replay/main.go
  das/aggregator.go
  das/archiving_storage_service.go
  das/bigcache_storage_service.go
  das/cache_storage_to_das_adapter.go
  das/das.go
  das/dasrpc/dasRpcClient.go
  das/dasrpc/dasRpcServer.go
  das/db_storage_service.go
  das/local_file_storage_service.go
  das/memory_backed_storage_service.go
  das/read_limited.go
  das/reader_aggregator_strategies_test.go
  das/redis_storage_service.go
  das/redundant_simple_das_reader.go
  das/redundant_storage_service.go
  das/restful_client.go
  das/restful_server.go
  das/s3_storage_service.go
  das/s3_storage_service_test.go
  das/sign_after_store_das.go
  das/simple_das_reader_aggregator.go
  das/storage_service.go
Labels: AnyTrust, cla-signed

#661 Add timeout and retry for DAS
  arbnode/node.go
  das/das.go
  das/dasrpc/rpc_aggregator.go
  das/retry_wrapper.go
  das/timeout_wrapper.go
  go.mod
  go.sum
Labels: AnyTrust, cla-signed

#670 Remove private token from checkout
  .github/workflows/arbitrator-ci.yml
  .github/workflows/ci.yml
  .github/workflows/docker.yml
  arbitrator/prover/test-cases/go/go.sum
Labels: cla-signed

#673 Remove trailing slash from health check
  das/restful_server.go
Labels: cla-signed

#674 Fix DAS eager sync sequencer inbox addr config
  arbnode/node.go
Labels: AnyTrust, cla-signed

#675 Fix no keys config
  arbnode/node.go
  das/restful_server.go
Labels: AnyTrust, cla-signed

#677 Add S3 DAS object prefix option and more logging
  das/s3_storage_service.go
Labels: AnyTrust, cla-signed

#684 Remove BLS key registration functionality
  arbos/arbosState/arbosstate.go
  arbos/blsTable/bls.go
  arbos/blsTable/bls_test.go
  contracts/src/precompiles/ArbBLS.sol
  precompiles/ArbBLS.go
  precompiles/ArbBLS_test.go
Labels: cla-signed

#680 L1 gas pricing: Don't post a batch if the only contents are a batch posting report
  arbnode/batch_poster.go
  system_tests/block_validator_test.go
  validator/challenge_manager.go
  validator/stateless_block_validator.go
Labels: cla-signed

#682 Update daserver docs for next release
  docs/das/daserver-instructions.md
Labels: AnyTrust, cla-signed

#687 Remove 0x from restful
  das/restful_client.go
  das/restful_server.go
  das/storage_service.go
  docs/das/daserver-instructions.md
Labels: AnyTrust, cla-signed

#662 Change some errors to warn - changes ported from classic
  broadcastclient/broadcastclient.go
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/utils.go
Labels: cla-signed

#688 Update das doc with v2.0.0-alpha.5 image
  docs/das/daserver-instructions.md
Labels: AnyTrust, cla-signed

#649 Lower geth's block gas limit to `2^50`
  arbos/l2pricing/l2pricing.go
Labels: ArbOS, consensus, cla-signed

#663 Update dapp_migration.md
  docs/migration/dapp_migration.md
Labels: cla-signed

#630 feat: destination address validation in validator wallet and gas refunder support
  contracts/src/bridge/SequencerInbox.sol
  contracts/src/libraries/IGasRefunder.sol
  contracts/src/rollup/IRollupLogic.sol
  contracts/src/rollup/RollupUserLogic.sol
  contracts/src/rollup/ValidatorWallet.sol
  contracts/src/rollup/ValidatorWalletCreator.sol
  contracts/src/test-helpers/RollupMock.sol
  contracts/test/contract/arbRollup.spec.ts
  contracts/test/contract/validatorWallet.spec.ts
  validator/staker.go
  validator/validator_wallet.go
Labels: contracts, cla-signed

#641 Refactor parseSequencerMessage and add fuzz target
  .github/workflows/ci.yml
  .gitignore
  arbcompress/compress_cgo.go
  arbnode/batch_poster.go
  arbstate/das_reader.go
  arbstate/inbox.go
  arbstate/inbox_test.go
Labels: ArbOS, cla-signed

#689 coordinator: myurl invalid by default
  arbnode/forwarder.go
  arbnode/seq_coordinator.go
Labels: node, cla-signed

#624 feat: efficient merkleprooflib saves 100s gas
  contracts/src/libraries/MerkleLib.sol
Labels: contracts, community-contributor, cla-signed

#623 fix: Outbox replay state management, saves ~15k gas per msg
  contracts/src/bridge/Outbox.sol
Labels: contracts, community-contributor, cla-signed

#690 End-to-end l1 gas pricing test
  arbos/addressSet/addressSet.go
  arbos/incomingmessage.go
  arbos/internal_tx.go
  arbos/l1pricing/batchPoster.go
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing/l1pricing_test.go
  contracts/src/precompiles/ArbOwner.sol
  precompiles/ArbGasInfo.go
  precompiles/ArbOwner.go
  system_tests/fees_test.go
  util/arbmath/math.go
Labels: cla-signed

#695 Remove trailing whitespace in Solidity to fix formatting
  contracts/src/libraries/MerkleLib.sol
Labels: contracts, cla-signed

#699 refactor inbox aliasing
  contracts/src/bridge/Inbox.sol
Labels: contracts, cla-signed

#698 refactor: sequencer inbox DAS changes
  contracts/src/bridge/ISequencerInbox.sol
  contracts/src/bridge/SequencerInbox.sol
Labels: contracts, cla-signed

#700 Remove wavm blocks
  arbitrator/prover/src/machine.rs
  contracts/src/challenge/ChallengeLib.sol
  contracts/src/osp/OneStepProver0.sol
  contracts/src/state/Deserialize.sol
  contracts/src/state/Machine.sol
  contracts/src/state/PcStack.sol
Labels: cla-signed

#696 Remove outdated comment in GetGenesisBlockNumber
  arbnode/transaction_streamer.go
Labels: cla-signed

#703 fix: use payable.call instead of payable.transfer
  contracts/src/rollup/RollupUserLogic.sol
Labels: contracts, cla-signed

#706 Enable parallel tests
  broadcastclient/broadcastclient_test.go
  das/aggregator_test.go
  das/restful_server_list_test.go
  das/restful_server_test.go
  system_tests/block_validator_test.go
  system_tests/bloom_test.go
  system_tests/das_test.go
  system_tests/delayedinboxlong_test.go
  system_tests/fees_test.go
  system_tests/initialization_test.go
  system_tests/outbox_test.go
  system_tests/retryable_test.go
  system_tests/seqfeed_test.go
  system_tests/seqinbox_test.go
  system_tests/staker_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: cla-signed

#710 Deploy tx timeout option
  cmd/deploy/deploy.go
Labels: cla-signed

#709 Restrict component estimation
  nodeInterface/NodeInterface.go
Labels: cla-signed

#712 Temporarily disable unsafe retryable entrypoints
  contracts/src/bridge/IInbox.sol
  contracts/src/bridge/Inbox.sol
Labels: cla-signed

#714 Sequencer and rollup owner deploy flags
  arbnode/node.go
  arbnode/sequencer.go
  cmd/deploy/deploy.go
  system_tests/common_test.go
Labels: cla-signed

#713 Add transaction sender whitelist to sequencer
  arbnode/node.go
  arbnode/sequencer.go
  system_tests/seq_whitelist_test.go
  system_tests/test_info.go
Labels: cla-signed

#716 test retries
  arbos/block_processor.go
  system_tests/staker_test.go
  validator/staker.go
Labels: cla-signed

#719 Fix test-node.bash
  arbnode/node.go
  arbnode/sequencer.go
  system_tests/seq_whitelist_test.go
  test-node.bash
Labels: cla-signed

#718 Download new WASM machine version in dockerfile for validator
  Dockerfile
Labels: cla-signed

#721 Add new anytrust chain config defaults
  cmd/nitro/nitro.go
Labels: cla-signed

#717 Assorted staker fixes resolving test flakiness
  arbutil/wait_for_l1.go
  validator/l1_validator.go
  validator/staker.go
  validator/validator_wallet.go
Labels: cla-signed

#722 Revert instead of panicking in precompiles if output ABI decoding fails
  precompiles/precompile.go
  validator/block_validator.go
Labels: cla-signed

#723 Bump nitro-contracts to 1.0.0-beta.6
  contracts/package.json
Labels: cla-signed

#728 Pricing time delta fix
  arbos/internal_tx.go
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing_test.go
Labels: ArbOS, consensus, cla-signed

#729 fix: add aliasing to utility method that covers all functions
  contracts/src/bridge/Inbox.sol
Labels: cla-signed

#735 Download Consensus V2 WAVM machine into docker image for validators
  Dockerfile
Labels: cla-signed

#737 Fix batch posting report balance transfer tracing
  arbos/internal_tx.go
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing_test.go
Labels: cla-signed

#736 Fix sequencer reorgs caused by delayed messages
  arbnode/delayed_seq_reorg_test.go
  arbnode/inbox_test.go
  arbnode/inbox_tracker.go
  arbnode/node.go
  arbnode/schema.go
  arbnode/transaction_streamer.go
  cmd/nitro/nitro.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/full_challenge_impl_test.go
  system_tests/seq_coordinator_test.go
Labels: node, cla-signed
