Repository OffchainLabs/nitro, pull requests merged in 2022-10, with the labels that each got.

#1209 Update docs to 2.0.7 and fix validator instructions
  docs/node-running/running-a-node.md
Labels: s

#1210 Fix err print in seq coordinator
  arbnode/seq_coordinator.go
Labels: s

#1203 Timeout requests if they have been sitting in queue too long
  arbnode/forwarder.go
  arbnode/sequencer.go
Labels: s

#1211 remove unnecessary error message from seq_coordinator
  arbnode/seq_coordinator.go
Labels: s

#1204 Add LastHeaderWithError
  util/headerreader/header_reader.go
Labels: s

#1216 Error when the L1 client returns bad transaction data
  arbnode/delayed.go
  arbnode/delayed_seq_reorg_test.go
  arbnode/sequencer_inbox.go
  arbutil/transaction_data.go
  das/syncing_fallback_storage.go
Labels: s

#1175 Add nonce cache to sequencer
  arbnode/sequencer.go
  arbnode/transaction_streamer.go
  arbnode/tx_pre_checker.go
  arbos/block_processor.go
  util/containers/lru.go
  util/containers/queue.go
Labels: s

#1218 Log tx sender in "validator address isn't whitelisted" log line
  validator/eoa_validator_wallet.go
  validator/staker.go
  validator/validator_wallet.go
Labels: s

#1221 Add consensus v7.1 WASM machine to docker
  Dockerfile
Labels: s

#1136 Coordinator sign asymmetric (has config changes)
  arbnode/dataposter/data_poster.go
  arbnode/dataposter/redis_storage.go
  arbnode/node.go
  arbnode/seq_coordinator.go
  arbnode/seq_coordinator_atomic_test.go
  broadcastclient/broadcastclient.go
  broadcastclient/broadcastclient_test.go
  cmd/relay/relay.go
  relay/relay.go
  system_tests/batch_poster_test.go
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/seq_coordinator_test.go
  system_tests/seqcompensation_test.go
  system_tests/seqfeed_test.go
  system_tests/staker_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
  util/redisutil/redis_coordinator.go
  util/signature/sign_verify.go
  util/signature/sign_verify_test.go
  util/signature/simple_hmac.go
  util/signature/verifier.go
  util/signature/verifier_test.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1222 Add `ChanRateLimiter`
  util/stopwaiter/stopwaiter.go
Labels: s

#1191 fix(testnode): add redis signer key to batch poster
  testnode-scripts/config.ts
Labels: s

#1228 Feature-gate llvm
  arbitrator/jit/Cargo.toml
  arbitrator/jit/src/machine.rs
Labels: s

#1225 Add support for database format versions
  arbnode/node.go
  arbnode/schema.go
Labels: s

#1223 testnode config update for asymmetric sequencer
  testnode-scripts/config.ts
Labels: s

#1234 Allow signer to not be defined if signature not required
  util/signature/verifier.go
Labels: s

#1235 Add livenessprobe to feed
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1238 Close connection before calling stop
  wsbroadcastserver/clientconnection.go
Labels: s

#1239 Ensure we don't exceed MaxDecompressedLen in batch poster
  arbnode/batch_poster.go
  arbstate/inbox.go
Labels: s

#1224 Replace panics on startup with nicer exits
  arbnode/arb_interface.go
  arbnode/forwarder.go
  arbnode/node.go
  broadcaster/broadcaster.go
  cmd/daserver/daserver.go
  cmd/nitro/init.go
  cmd/nitro/nitro.go
  cmd/relay/relay.go
  cmd/util/confighelpers/configuration.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1245 Generally saturate and log a warning instead of erroring on overflow
  arbos/l1pricing/batchPoster.go
  arbos/l1pricing/l1pricing.go
  arbos/l2pricing/l2pricing.go
  arbos/retryables/retryable.go
  arbos/storage/storage.go
  arbos/storage/storage_test.go
Labels: s

#1233 [Instrumentation] Add Pprof Support to Nitro
  cmd/genericconf/server.go
  cmd/nitro/nitro.go
Labels: s

#1247 Build in LLVM for the JIT validator in docker
  Dockerfile
  Makefile
Labels: s

#1250 Fix L1 block number being one too high
  arbos/block_processor.go
  arbos/blockhash/blockhash.go
  arbos/blockhash/blockhash_test.go
  arbos/internal_tx.go
  arbos/tx_processor.go
Labels: s

#1254 add arbiscan goerli explorer to docs
  docs/public-chains.md
Labels: docs, s

#1257 Minor updates to whitepaper
  docs/Nitro-whitepaper.pdf
Labels: docs, s

#1258 Do not explicitly close client chan to prevent panic
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1261 Make go tooling ignore arbitrator directory
  arbitrator/go.mod
Labels: s

#1260 Always try to post the next transaction in the batch poster
  arbnode/batch_poster.go
  arbnode/sequencer.go
  system_tests/batch_poster_test.go
Labels: s

#1262 Remove one-time das upgrade script
  cmd/one-time-das-upgrade/upgrade.go
Labels: s

#1248 Improve state fuzzer
  system_tests/state_fuzz_test.go
Labels: s

#1264 Don't fail CI if the codecov upload fails
  .github/workflows/ci.yml
  .github/workflows/contract-tests.yml
Labels: s

#1266 Use a smart contract wallet for test node validators
  testnode-scripts/config.ts
Labels: s

#1240 Improve logging when feed goes down
  arbnode/node.go
  broadcastclient/broadcastclient.go
  broadcastclient/broadcastclient_test.go
  broadcastclients/broadcastclients.go
  broadcaster/sequencenumbercatchupbuffer.go
  cmd/nitro/nitro.go
  relay/relay.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1267 Add extra metric to measure rate new connections are made
  wsbroadcastserver/clientmanager.go
Labels: s

#1256 Use batchposter address for gascap adjustment
  nodeInterface/virtual-contracts.go
Labels: s

#1189 Deploy token bridge with test node using sdk
  docker-compose.yaml
  test-node.bash
  testnode-tokenbridge/Dockerfile
Labels: s

#1263 Make l1 age warning configurable
  system_tests/common_test.go
  system_tests/full_challenge_impl_test.go
  system_tests/staker_test.go
  system_tests/test_info.go
  util/headerreader/header_reader.go
Labels: s

#1271 Stop without wait when removing client
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/clientmanager.go
Labels: s

#1279 use nova arbiscan explorer in docs
  docs/public-chains.md
  docs/useful-addresses.md
Labels: docs, s

#1281 Fix relay handling of confirm message
  arbnode/node.go
  broadcastclient/broadcastclient.go
  broadcastclient/broadcastclient_test.go
  broadcastclients/broadcastclients.go
  broadcaster/sequencenumbercatchupbuffer.go
  relay/relay.go
Labels: s

#1289 Free queue elements as soon as they are popped
  util/containers/queue.go
Labels: s

#1214 Include gas cost in batch posting report message when parsing (requires relay upgrade)
  arbnode/delayed.go
  arbnode/inbox_reader.go
  arbnode/inbox_tracker.go
  arbnode/node.go
  arbnode/schema.go
  arbnode/sequencer_inbox.go
  arbnode/transaction_streamer.go
  arbos/block_processor.go
  arbos/incomingmessage.go
  arbos/incomingmessage_test.go
  arbstate/geth_test.go
  arbstate/inbox.go
  arbstate/inbox_fuzz_test.go
  cmd/replay/main.go
  system_tests/retryable_test.go
  system_tests/state_fuzz_test.go
Labels: s

#1293 Fix Shadowed Variables
  arbcompress/compress_common.go
  cmd/nitro/nitro.go
Labels: s

#1292 Address PR review comments on batch posting report PR
  arbos/incomingmessage.go
Labels: s

#1299 Cleanup: format go imports
  arbos/addressSet/addressSet_test.go
  arbos/l1pricing/batchPoster_test.go
  cmd/relay/config_test.go
  precompiles/ArbRetryableTx_test.go
  util/contracts/batch_poster_verifier.go
  util/signature/datasigner.go
Labels: s

#1298 Cleanup: non-capitalized error strings
  arbnode/delayed_sequencer.go
  arbos/block_processor.go
  arbos/util/transfer.go
  arbos/util/util.go
  arbstate/das_reader.go
  cmd/daserver/daserver.go
  cmd/replay/db.go
  das/aggregator.go
  das/archiving_storage_service.go
  das/factory.go
  das/local_file_storage_service.go
  das/reader_aggregator_strategies.go
  das/rest_server_list.go
  das/restful_client.go
  das/simple_das_reader_aggregator.go
  das/storage_service.go
  precompiles/ArbAggregator.go
  precompiles/ArbSys.go
  precompiles/ArbosTest.go
  precompiles/wrapper.go
  validator/jit_machine.go
  validator/rollup_watcher.go
Labels: s

#1300 rename `arb-specific-things` to `arbitrum-ethereum-differences`
  docs/arbitrum-ethereum-differences.md
  docs/getting-started-devs.md
Labels: s

#1282 Add consensus v9 WASM machine to docker
  Dockerfile
Labels: s

#1241 Include cost of proxy contract in gas refunder enabled costs
  contracts/src/libraries/IGasRefunder.sol
Labels: contracts, s
