Repository OffchainLabs/nitro, pull requests merged in 2022-05, with the labels that each got.

#527 Das aggregator
  arbnode/node.go
  arbstate/das_reader.go
  blsSignatures/blsSignatures_test.go
  cmd/daserver/daserver.go
  cmd/replay/main.go
  contracts/src/bridge/Inbox.sol
  das/aggregator.go
  das/aggregator_test.go
  das/das.go
  das/das_test.go
  das/dasrpc/dasRpcClient.go
  das/local_disk_das.go
  das/timeout_wrapper.go
  validator/stateless_block_validator.go
Labels: AnyTrust

#569 Fix {i32,i64}.shr_s OneStepProof impl
  arbitrator/prover/test-cases/math.wat
  contracts/src/osp/OneStepProverMath.sol
Labels: arbitrator, contracts

#558 Print out failed block number and hash on arbitrator error
  arbitrator/prover/src/lib.rs
  arbitrator/prover/src/machine.rs
  arbitrator/prover/src/main.rs
  validator/block_validator.go
  validator/machine.go
Labels: arbitrator, node

#580 chore: add whitelist of files to publish to npm
  contracts/package.json
Labels: contracts

#560 Retrieve arbitrator preimages on demand
  arbitrator/prover/src/lib.rs
  arbitrator/prover/src/machine.rs
  arbitrator/prover/src/main.rs
  arbitrator/prover/src/utils.rs
  arbnode/node.go
  arbnode/transaction_streamer.go
  system_tests/full_challenge_impl_test.go
  system_tests/staker_test.go
  validator/block_validator.go
  validator/challenge_manager.go
  validator/l1_validator.go
  validator/machine.go
  validator/preimage_cache.go
  validator/preimage_resolver.go
  validator/staker.go
  validator/stateless_block_validator.go
Labels: arbitrator

#534 Wasmparser Arbitrator frontend
  Makefile
  arbitrator/Cargo.lock
  arbitrator/prover/Cargo.toml
  arbitrator/prover/src/binary.rs
  arbitrator/prover/src/host.rs
  arbitrator/prover/src/lib.rs
  arbitrator/prover/src/machine.rs
  arbitrator/prover/src/main.rs
  arbitrator/prover/src/memory.rs
  arbitrator/prover/src/utils.rs
  arbitrator/prover/src/value.rs
  arbitrator/prover/src/wavm.rs
Labels: arbitrator

#588 Anytrust key config
  Makefile
  arbnode/node.go
  cmd/daserver/daserver.go
  cmd/datool/datool.go
  cmd/nitro/config_test.go
  das/aggregator.go
  das/aggregator_test.go
  das/das.go
  das/das_test.go
  das/dasrpc/dasRpcClient.go
  das/dasrpc/rpc_aggregator.go
  das/key_utils.go
  das/local_disk_das.go
  system_tests/block_validator_test.go
  system_tests/seqfeed_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: AnyTrust

#590 docs: update dapp_migration.md
  docs/migration/dapp_migration.md
Labels: docs

#584 feat: add magic value to inbox to surface retryable creation data
  contracts/src/bridge/IInbox.sol
  contracts/src/bridge/Inbox.sol
Labels: contracts

#577 Add L1 DAS key management
  arbnode/batch_poster.go
  arbnode/node.go
  arbstate/das_reader.go
  arbstate/inbox.go
  blsSignatures/blsSignatures.go
  cmd/datool/datool.go
  cmd/replay/main.go
  contracts/src/bridge/ISequencerInbox.sol
  contracts/src/bridge/SequencerInbox.sol
  contracts/src/rollup/IRollupLogic.sol
  contracts/src/rollup/RollupAdminLogic.sol
  contracts/src/rollup/RollupUserLogic.sol
  contracts/test/contract/arbRollup.spec.ts
  das/aggregator.go
  das/aggregator_test.go
  das/das.go
  das/das_test.go
  das/dasrpc/dasRpcClient.go
  das/dasrpc/dasRpcServer.go
  das/local_disk_das.go
  das/timeout_wrapper.go
  das/wireFormat.proto
  system_tests/block_validator_test.go
  system_tests/seqfeed_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
  validator/stateless_block_validator.go
Labels: contracts, consensus, AnyTrust

#596 Arbitrator: Add a safety check that the number of modules is a u32
  arbitrator/prover/src/machine.rs
Labels: arbitrator

#599 Fix CBytes IntoIterator impl
  arbitrator/prover/src/utils.rs
Labels: arbitrator

#595 Daserver packaging
  Dockerfile
  arbnode/node.go
  cmd/daserver/daserver.go
  das/das.go
  docs/das/daserver-instructions.md
  system_tests/block_validator_bench_test.go
  system_tests/block_validator_test.go
  system_tests/seqfeed_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: AnyTrust

#591 Fix additional das comments from #588
  arbnode/node.go
  cmd/daserver/daserver.go
  cmd/nitro/nitro.go
  cmd/relay/relay.go
  cmd/util/configuration.go
Labels: AnyTrust

#598 Fetch keyset from L1
  arbnode/node.go
  contracts/yarn.lock
  das/aggregator.go
  das/chain_fetch_das.go
  das/das.go
  das/dasrpc/dasRpcServer.go
  das/local_disk_das.go
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/seqfeed_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: AnyTrust

#571 Add arbitrator one step proof fuzzer
  arbitrator/prover/fuzz/.gitignore
  arbitrator/prover/fuzz/Cargo.lock
  arbitrator/prover/fuzz/Cargo.toml
  arbitrator/prover/fuzz/fuzz_targets/osp.rs
  arbitrator/prover/src/lib.rs
  arbitrator/prover/src/machine.rs
  arbitrator/prover/src/main.rs
  arbitrator/prover/src/memory.rs
  arbitrator/prover/test-cases/memory.wat
Labels: arbitrator

#606 Fix GraphQL config overwriting HTTP config
  cmd/genericconf/server.go
Labels: node

#608 Get Store signer from batch poster wallet
  arbnode/node.go
  cmd/genericconf/wallet.go
  cmd/nitro/nitro.go
  go.mod
  go.sum
Labels: AnyTrust

#610 Switch DAS server over to rpc
  cmd/daserver/daserver.go
  das/dasrpc/dasRpcClient.go
  das/dasrpc/dasRpcServer.go
  das/dasrpc/rpc_aggregator.go
  das/dasrpc/rpc_test.go
  system_tests/das_test.go
Labels: AnyTrust

#612 Aggregator dumps keyset
  das/aggregator.go
Labels: AnyTrust

#614 Update docs for goerli devnet
  docs/das/daserver-instructions.md
Labels: AnyTrust

#615 Remove store-signer das option
  das/das.go
Labels: AnyTrust

#604 Anytrust storage refactor
  arbnode/node.go
  cmd/daserver/daserver.go
  cmd/nitro/nitro.go
  das/aggregator.go
  das/aggregator_test.go
  das/das_test.go
  das/dasrpc/rpc_aggregator.go
  das/dasrpc/rpc_test.go
  das/db_storage_service.go
  das/local_disk_das.go
  das/memory_backed_storage_service.go
  das/redundant_storage_service.go
  das/redundant_storage_test.go
  das/storage_service.go
  go.mod
  go.sum
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/full_challenge_impl_test.go
Labels: AnyTrust

#618 RESTful das server
  Makefile
  arbitrator/prover/test-cases/go/go.sum
  arbstate/das_reader.go
  arbstate/inbox.go
  cmd/dasrest/dasrest.go
  cmd/datool/datool.go
  cmd/replay/main.go
  das/aggregator.go
  das/aggregator_test.go
  das/archiving_storage_service.go
  das/archiving_storage_service_test.go
  das/chain_fetch_das.go
  das/das.go
  das/das_test.go
  das/dasrpc/dasRpcClient.go
  das/dasrpc/dasRpcServer.go
  das/dasrpc/rpc_test.go
  das/db_storage_service.go
  das/local_disk_das.go
  das/memory_backed_storage_service.go
  das/redundant_simple_das_reader.go
  das/redundant_storage_service.go
  das/redundant_storage_test.go
  das/restful_server.go
  das/restful_server_test.go
  das/storage_service.go
  das/timeout_wrapper.go
  go.mod
  go.sum
Labels: AnyTrust

#622 Das reader for non sequencers
  arbnode/inbox_tracker.go
  arbnode/node.go
  das/chain_fetch_das.go
  validator/block_validator.go
  validator/challenge_manager.go
  validator/l1_validator.go
  validator/staker.go
  validator/stateless_block_validator.go
Labels: AnyTrust

#625 Rest client
  cmd/dasrest/dasrest.go
  cmd/datool/datool.go
  das/restful_client.go
  das/restful_server.go
  das/restful_server_test.go
  das/storage_service.go
Labels: AnyTrust

#627 Fallback StorageService
  das/fallback_storage_service.go
  das/fallback_storage_service_test.go
  util/arbmath/math_test.go
Labels: AnyTrust

#620 Update Inbox.sol
  contracts/src/bridge/Inbox.sol
Labels: contracts

#607 Add s3, redis, bigcache storage service
  arbnode/node.go
  cmd/daserver/daserver.go
  das/aggregator.go
  das/aggregator_test.go
  das/bigcache_storage_service.go
  das/bigcache_storage_service_test.go
  das/das.go
  das/das_test.go
  das/dasrpc/rpc_aggregator.go
  das/dasrpc/rpc_test.go
  das/local_disk_das.go
  das/redis_storage_service.go
  das/redis_storage_service_test.go
  das/s3_storage_service.go
  das/s3_storage_service_test.go
  docs/das/daserver-instructions.md
  go.mod
  go.sum
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/seqfeed_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: AnyTrust

#626 Rest client aggregator
  das/reader_aggregator_strategies.go
  das/reader_aggregator_strategies_test.go
  das/restful_client.go
  das/simple_das_reader_aggregator.go
  das/simple_das_reader_aggregator_test.go
Labels: AnyTrust

#638 Sync storage server from chain
  das/sync_from_l1_chain.go
Labels: AnyTrust

#632 Enable/Disable data deletion and Expiration Policy API
  das/archiving_storage_service.go
  das/bigcache_storage_service.go
  das/db_storage_service.go
  das/local_disk_das.go
  das/memory_backed_storage_service.go
  das/redis_storage_service.go
  das/redundant_storage_service.go
  das/s3_storage_service.go
  das/storage_service.go
Labels: AnyTrust
