Repository OffchainLabs/nitro, pull requests merged in 2022-08, with the labels that each got.

#878 Use gotestsum for CI again
  .github/workflows/ci.yml
Labels: CI, cla-signed

#881 Update daserver instructions for mainnet
  docs/das/daserver-instructions.md
Labels: cla-signed

#882 Add metrics to daserver docs
  docs/das/daserver-instructions.md
Labels: AnyTrust, cla-signed

#880 Fix unnecessary inbox reader queries
  arbnode/inbox_reader.go
Labels: node, cla-signed

#876 Use saturating arithmetic
  arbos/l1pricing/l1pricing.go
Labels: cla-signed

#885 Clear loser challenge when challenge completed
  contracts/src/rollup/RollupUserLogic.sol
Labels: contracts, cla-signed

#887 Update dapp_migration.md
  docs/migration/dapp_migration.md
Labels: cla-signed

#889 Fix sequencer tx rejection
  arbos/block_processor.go
Labels: cla-signed

#890 Documentation for daserver extra signing key
  docs/das/daserver-instructions.md
Labels: cla-signed

#895 Add test of sequencer rejecting transactions
  arbnode/sequencer.go
  contracts/src/mocks/Simple.sol
  system_tests/seq_reject_test.go
  system_tests/seqfeed_test.go
Labels: cla-signed

#896 Small sequencer fixes
  arbnode/sequencer.go
Labels: cla-signed

#891 retry transactions if no sequencer found
  arbnode/forwarder.go
  arbnode/node.go
  arbnode/sequencer.go
Labels: cla-signed

#892 Datool wallet file
  cmd/datool/datool.go
Labels: cla-signed

#900 Add option to generate hash in DaTool
  cmd/datool/datool.go
Labels: AnyTrust, cla-signed

#901 New public DAS mirror list URL for docs
  docs/das/daserver-instructions.md
Labels: cla-signed

#886 Test upgradability of RollupProxy
  contracts/src/libraries/AdminFallbackProxy.sol
  contracts/src/libraries/DoubleLogicUUPSUpgradeable.sol
  contracts/src/rollup/RollupAdminLogic.sol
  contracts/test/contract/arbRollup.spec.ts
Labels: testing, cla-signed

#906 Infrustructer fee account edits
  arbos/tx_processor.go
  precompiles/precompile.go
  precompiles/precompile_test.go
  system_tests/infra_fee_test.go
Labels: cla-signed

#904 Fix `ioutil` lint
  arbnode/seq_coordinator.go
  cmd/datool/datool.go
  cmd/deploy/deploy.go
  das/key_utils.go
  das/restful_client.go
  das/sign_after_store_das.go
  solgen/gen.go
  statetransfer/jsondatareader.go
  validator/nitro_machine.go
  wavmio/stub.go
  wsbroadcastserver/utils.go
Labels: cla-signed

#907 Add consensus v5 WAVM machine to docker
  Dockerfile
Labels: cla-signed

#905 Fix LOG15_ERROR msgs from logging odd # of args
  das/util.go
Labels: cla-signed

#899 Add Default Cache for restful api
  das/restful_server.go
Labels: AnyTrust, cla-signed

#916 Update license
  LICENSE
Labels: cla-signed

#921 Fix issue where nitro config dump not clearing l2 dev-wallet password
  cmd/nitro/nitro.go
Labels: cla-signed

#922 Check that solidity methods exist
  precompiles/precompile.go
Labels: cla-signed

#923 Fix watchtower validators and add test
  system_tests/staker_test.go
  validator/staker.go
  validator/validator_wallet.go
Labels: node, cla-signed

#926 Arbowner public fix
  precompiles/ArbOwnerPublic.go
  precompiles/ArbOwner_test.go
Labels: consensus, cla-signed

#929 Print aggregate signer mask in error msg
  das/aggregator.go
Labels: AnyTrust, cla-signed

#930 Add ability to send random data from datool
  cmd/datool/datool.go
Labels: cla-signed

#931 Disable RetryWrapper in RPC Aggregator
  das/dasrpc/rpc_aggregator.go
Labels: cla-signed

#932 Set correct AssumedHonest for Retrieve test
  das/aggregator_test.go
Labels: cla-signed

#934 Add 0x hexadecimal marker to log message
  das/aggregator.go
Labels: cla-signed

#902 add 'gentle introduction' docs page
  docs/intro.md
  docs/intro/intro.md
Labels: docs, cla-signed

#883 Process headers on broadcast feed connect
  arbnode/node.go
  arbnode/transaction_streamer.go
  broadcastclient/broadcastclient.go
  broadcastclient/broadcastclient_test.go
  broadcaster/broadcaster.go
  broadcaster/broadcaster_test.go
  broadcaster/sequencenumbercatchupbuffer.go
  broadcaster/sequencenumbercatchupbuffer_test.go
  cmd/nitro/nitro.go
  cmd/relay/relay.go
  relay/relay.go
  system_tests/block_hash_test.go
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/delayedinbox_test.go
  system_tests/delayedinboxlong_test.go
  system_tests/fees_test.go
  system_tests/full_challenge_impl_test.go
  system_tests/retryable_test.go
  system_tests/seq_coordinator_test.go
  system_tests/seq_reject_test.go
  system_tests/seqcompensation_test.go
  system_tests/seqfeed_test.go
  system_tests/seqinbox_test.go
  system_tests/staker_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
  validator/block_validator.go
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/clientmanager.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: cla-signed

#944 Initialize broadcast server early
  arbnode/node.go
  broadcastclient/broadcastclient_test.go
  broadcaster/broadcaster.go
  broadcaster/broadcaster_test.go
  relay/relay.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: cla-signed

#936 add 'why nitro' docs page
  docs/why_nitro.md
Labels: docs, cla-signed

#942 Log a warning if the latest L1 header is at least 5 minutes old
  util/headerreader/header_reader.go
Labels: node, cla-signed

#946 add mainnet beta page (same as old/current docs)
  docs/mainnet_beta.md
Labels: docs, cla-signed

#903 Update Natspec and migration doc
  contracts/src/bridge/Inbox.sol
  contracts/src/node-interface/NodeInterface.sol
  docs/migration/dapp_migration.md
Labels: docs, contracts, cla-signed

#925 MerkleLib.calculateRoot gas optimization
  contracts/src/libraries/MerkleLib.sol
Labels: contracts, cla-signed

#945 Fix from and currentHeight aliasing in inbox reader
  arbnode/delayed_sequencer.go
  arbnode/inbox_reader.go
Labels: node, cla-signed

#935 add node running / node provider docs
  docs/node_running/node_providers.md
  docs/node_running/running_a_node.md
Labels: docs, cla-signed

#911 Update blockhash explanation
  docs/migration/dapp_migration.md
Labels: docs, cla-signed

#919 add glossary to docs
  docs/intro/glossary.md
Labels: docs, cla-signed

#949 Add missingDelayed and missingSequencer to inbox reader logs
  arbnode/inbox_reader.go
Labels: node, cla-signed

#953 Fix arbitrator clippy lints
  arbitrator/prover/src/binary.rs
  arbitrator/prover/src/memory.rs
Labels: arbitrator, cla-signed

#954 Lowercase docs
  docs/arbos/arbos.md
  docs/arbos/common-precompiles.md
  docs/arbos/gas.md
  docs/arbos/geth.md
  docs/arbos/l1-pricing.md
  docs/arbos/precompiles.md
  docs/inside-anytrust.md
  docs/intro/intro.md
  docs/mainnet-beta.md
  docs/migration/dapp_migration.md
  docs/node-running/node-providers.md
  docs/node-running/running-a-node.md
  docs/proving/challenge-manager.md
  docs/proving/osp-assumptions.md
  docs/proving/wasm-to-wavm.md
  docs/proving/wavm-custom-opcodes.md
  docs/proving/wavm-floats.md
  docs/proving/wavm-modules.md
  docs/why-nitro.md
Labels: docs, cla-signed

#948 update L1 pricing summary in docs
  docs/arbos/gas.md
Labels: docs, cla-signed

#957 fix broken link
  docs/intro/intro.md
Labels: docs, cla-signed

#956 Error recovery in RestfulServerListFetchDaemon
  das/rest_server_list.go
  das/restful_server_list_test.go
Labels: cla-signed

#963 Populate ECDSA caches early in the replay binary
  cmd/replay/main.go
Labels: cla-signed

#962 Add arbitrator prover flag to only profile after host io
  arbitrator/prover/src/lib.rs
  arbitrator/prover/src/machine.rs
  arbitrator/prover/src/main.rs
Labels: arbitrator, cla-signed

#947 add sequencer docs
  docs/sequencer.md
Labels: docs, cla-signed

#966 Document ability of retryables in nitro to deploy contracts
  docs/migration/dapp_migration.md
Labels: docs, cla-signed

#959 Delete feed from previous confirmation
  arbnode/inbox_tracker.go
  broadcastclient/broadcastclient_test.go
  broadcaster/broadcaster.go
  broadcaster/broadcaster_test.go
  broadcaster/sequencenumbercatchupbuffer.go
  broadcaster/sequencenumbercatchupbuffer_test.go
Labels: cla-signed

#952 Add inside arbitrum nitro
  docs/inside-arbitrum-nitro/geth-sandwich.png
  docs/inside-arbitrum-nitro/inside_arbitrum_nitro.md
  docs/inside-arbitrum-nitro/seq-then-exec.png
Labels: docs, cla-signed

#967 update quicknode docs
  docs/node-running/node-providers.md
Labels: docs, cla-signed

#964 Panic if keyset is invalid in replay binary
  arbnode/inbox_tracker.go
  arbstate/das_reader.go
  arbstate/inbox.go
  arbstate/inbox_fuzz_test.go
  blsSignatures/blsSignatures.go
  cmd/replay/main.go
  das/key_utils.go
  das/syncing_fallback_storage.go
  system_tests/state_fuzz_test.go
  validator/stateless_block_validator.go
Labels: cla-signed

#940 Allow a backwards delayed reorg without hard reorgs enabled
  arbnode/delayed_seq_reorg_test.go
  arbnode/delayed_sequencer.go
  arbnode/inbox_reader.go
  arbnode/inbox_tracker.go
Labels: node, cla-signed

#968 Silence old timestamp warning
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing_test.go
Labels: cla-signed

#969 Update dapp_migration.md
  docs/migration/dapp_migration.md
Labels: docs, cla-signed

#965 Fix expired retryable deletion on migration
  arbos/arbosState/initialize.go
Labels: ArbOS, consensus, cla-signed

#939 add faqs to docs
  docs/faqs/anytrust-vs-rollup.md
  docs/faqs/beta-status.md
  docs/faqs/how-fees.md
  docs/faqs/seq-or-val.md
  docs/faqs/what-if-dispute.md
Labels: docs, cla-signed

#972 Test aliasing
  contracts/src/mocks/Simple.sol
  precompiles/ArbSys.go
  system_tests/aliasing_test.go
  system_tests/bloom_test.go
  system_tests/common_test.go
  system_tests/delayedinbox_test.go
  system_tests/estimation_test.go
  system_tests/infra_fee_test.go
  system_tests/retryable_test.go
  system_tests/seq_reject_test.go
  system_tests/test_info.go
Labels: cla-signed

#941 Query a dynamic block range for inbox messages
  arbnode/inbox_reader.go
Labels: node, cla-signed

#848 Refactor contract interfaces
  contracts/deploy/InboxStubCreator.js
  contracts/src/bridge/Bridge.sol
  contracts/src/bridge/IBridge.sol
  contracts/src/bridge/IInbox.sol
  contracts/src/bridge/IOutbox.sol
  contracts/src/bridge/ISequencerInbox.sol
  contracts/src/bridge/Inbox.sol
  contracts/src/bridge/Outbox.sol
  contracts/src/bridge/SequencerInbox.sol
  contracts/src/mocks/BridgeStub.sol
  contracts/src/mocks/InboxStub.sol
  contracts/src/test-helpers/OutboxWithoutOptTester.sol
Labels: contracts, cla-signed

#975 Hot reload using reflection
  arbnode/node.go
  cmd/nitro/config_test.go
  cmd/nitro/nitro.go
Labels: cla-signed

#978 Set better arbos defaults for new chains
  arbnode/api.go
  arbos/arbosState/arbosstate.go
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing_test.go
  arbos/l2pricing/l2pricing.go
  arbos/l2pricing/model.go
  system_tests/block_validator_test.go
  system_tests/fees_test.go
  system_tests/test_info.go
Labels: consensus, cla-signed

#879 Patch rollup contracts and comments
  contracts/src/bridge/IOutbox.sol
  contracts/src/bridge/Inbox.sol
  contracts/src/bridge/Outbox.sol
  contracts/src/libraries/AdminFallbackProxy.sol
  contracts/src/libraries/DoubleLogicUUPSUpgradeable.sol
  contracts/src/precompiles/ArbSys.sol
  contracts/src/rollup/RollupAdminLogic.sol
  contracts/src/rollup/RollupCore.sol
  contracts/src/rollup/RollupCreator.sol
  contracts/src/rollup/RollupEventInbox.sol
  contracts/src/rollup/RollupProxy.sol
  contracts/src/rollup/RollupUserLogic.sol
  contracts/test/contract/arbRollup.spec.ts
Labels: contracts, cla-signed

#971 Use rpc aggregator only for stores
  arbnode/batch_poster.go
  arbnode/node.go
  cmd/daserver/daserver.go
  cmd/datool/datool.go
  das/aggregator_test.go
  das/chain_fetch_das.go
  das/das.go
  das/dasRpcClient.go
  das/dasRpcServer.go
  das/extra_signature_checker_test.go
  das/factory.go
  das/panic_wrapper.go
  das/rpc_aggregator.go
  das/rpc_test.go
  das/store_signing.go
  das/timeout_wrapper.go
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/seqfeed_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: AnyTrust, cla-signed

#974 Remove rpc store code
  arbnode/node.go
  cmd/datool/datool.go
  das/aggregator.go
  das/aggregator_test.go
  das/dasRpcClient.go
  das/dasRpcServer.go
  das/rpc_test.go
Labels: AnyTrust, cla-signed

#984 Use rpc aggregator only for stores
  arbnode/node.go
  cmd/datool/datool.go
  das/aggregator.go
  das/aggregator_test.go
  das/dasRpcClient.go
  das/dasRpcServer.go
  das/rpc_test.go
Labels: cla-signed

#979 Make ConfigFetcher an interface
  arbnode/node.go
  cmd/nitro/nitro.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/full_challenge_impl_test.go
Labels: cla-signed

#981 classic-msg is not always expected
  arbnode/node.go
Labels: cla-signed

#989 Update dapp_migration.md
  docs/migration/dapp_migration.md
Labels: cla-signed

#988 Live node config edits
  cmd/nitro/config_test.go
  cmd/nitro/nitro.go
Labels: cla-signed

#991 init: create tx lookup entries in parallel
  cmd/nitro/nitro.go
Labels: cla-signed

#998 Improve Node lifecycle management
  arbnode/node.go
Labels: node

#987 Don't print error when context cancelled
  util/headerreader/header_reader.go
Labels: cla-signed

#1003 add l2-to-l1 message docs and x-chain message summary docs
  docs/arbos/l2-to-l1-messaging.md
  docs/for-devs/cross-chain-messsaging.md
  docs/inside-arbitrum-nitro/inside-arbitrum-nitro.md
Labels: docs, cla-signed

#1004 Use 🖋️ as cla-signed label
  .clabot
Labels: cla-signed

#997 fix batch typo
  contracts/src/node-interface/NodeInterface.sol
Labels: cla-signed

#977 initial state migration doc
  docs/migration/state_migration.md
Labels: docs, cla-signed

#1000 Tx lookup init
  cmd/nitro/init.go
  cmd/nitro/nitro.go
Labels: cla-signed

#1010 rename to state-migration.md (consistent casing)
  docs/migration/state-migration.md
Labels: docs, cla-signed

#937 Tx lifecycle / finality docs
  docs/tx-lifecycle.md
Labels: docs, cla-signed

#1011 Rename dapp_migration.md to dapp-migration.md
  docs/migration/dapp-migration.md
Labels: docs, cla-signed

#1014 Parallelize tx lookup index generation by keeping failed txs in memory
  cmd/nitro/init.go
Labels: cla-signed

#993 Error instead of panicking on new cert versions
  arbstate/inbox.go
Labels: ArbOS, consensus, cla-signed

#1016 fix link
  docs/faqs/how-fees.md
Labels: docs, cla-signed

#1015 Configurable merge finality
  arbnode/delayed_sequencer.go
Labels: cla-signed

#1012 Shorten cla-bot label
  .clabot
Labels: cla-signed

#1017 Add consensus v6 WAVM machine to docker
  Dockerfile
Labels: cla-signed, s

#1009 Fix race condition on program exit
  wsbroadcastserver/wsbroadcastserver.go
Labels: cla-signed, s

#1019 Add Nitro whitepaper
  docs/Nitro-whitepaper.pdf
Labels: docs, s

#1018 Setup rollup production config
  arbnode/node.go
  cmd/deploy/deploy.go
  system_tests/common_test.go
Labels: s

#1020 Fix handling of zero RPC gas cap meaning unlimited
  nodeInterface/virtual-contracts.go
Labels: node, s

#1023 Fix relay issue printing help message
  cmd/daserver/daserver.go
  cmd/nitro/nitro.go
Labels: s

#1027 Add configurable interval to create assertions at
  validator/l1_validator.go
  validator/staker.go
Labels: s

#1035 Rename dapp-migration.md to dapp_migration.md
  docs/migration/dapp_migration.md
Labels: docs, s

#1040 remove landing / slug
  docs/intro/intro.md
Labels: s

#951 Add a gas margin to the batch poster
  arbnode/batch_poster.go
Labels: cla-signed, s

#1034 Separate stateless block validation
  arbnode/api.go
  arbnode/node.go
  arbstate/inbox.go
  das/restful_server.go
  system_tests/common_test.go
  system_tests/seqfeed_test.go
  system_tests/staker_test.go
  validator/block_validator.go
  validator/stateless_block_validator.go
Labels: s

#1022 add section to delays faq
  docs/faqs/what-if-dispute.md
Labels: docs, s

#1036 add assertion tree docs page
  docs/assertion-tree.md
  docs/assertionTree.png
Labels: docs, s

#1021 updated "differences with ethereum" docs (overview, block #s and time, solidity support)
  docs/arb-specific-things.md
  docs/solidity-support.md
  docs/time.md
Labels: docs, s

#1032 Validator assumevalid
  validator/block_validator.go
  validator/staker.go
  validator/validator_wallet.go
Labels: s

#973 add LiveNodeConfig
  arbnode/node.go
  arbnode/sequencer.go
  cmd/genericconf/config.go
  cmd/nitro/config_test.go
  cmd/nitro/nitro.go
Labels: cla-signed, s

#1008 Data poster signing
  arbnode/dataposter/data_poster.go
  arbnode/dataposter/redis_storage.go
  arbnode/seq_coordinator.go
  arbnode/seq_coordinator_atomic_test.go
  cmd/nitro/nitro.go
  system_tests/seq_coordinator_test.go
  testnode-scripts/config.ts
  util/simple_hmac/simple_hmac.go
Labels: cla-signed

#1043 update useful-adddresses
  docs/useful-addresses.md
Labels: docs, s

#1029 token bridge docs
  docs/asset-bridging.md
  docs/bridge_deposits.png
  docs/bridge_withdrawals.png
  docs/gatewayUML.svg
Labels: docs, s

#1048 Contract changes for the data poster
  contracts/deploy/BridgeCreator.js
  contracts/deploy/SequencerInbox.js
  contracts/src/bridge/Bridge.sol
  contracts/src/bridge/IBridge.sol
  contracts/src/bridge/ISequencerInbox.sol
  contracts/src/bridge/SequencerInbox.sol
  contracts/src/libraries/Error.sol
  contracts/src/mocks/BridgeStub.sol
  contracts/src/mocks/SequencerInboxStub.sol
  contracts/src/rollup/RollupAdminLogic.sol
  contracts/src/test-helpers/BridgeTester.sol
  contracts/test/prover/one-step-proof.ts
  system_tests/seqinbox_test.go
Labels: s

#1049 add prover addresses to docs
  docs/useful-addresses.md
Labels: docs, s

#1051 add arb1 nitro snapshot checksum and size to docs
  docs/node-running/running-a-node.md
Labels: docs, s

#1050 Update classic node doc for 1.4.5
  docs/node-running/running-a-classic-node.md
Labels: docs, s

#1056 Make sequencer pending tx queue size configurable
  arbnode/node.go
  arbnode/sequencer.go
Labels: node, s
