Repository OffchainLabs/nitro, pull requests merged in 2022-11, with the labels that each got.

#1301 Bump the database schema version
  arbnode/schema.go
Labels: s

#1219 JIT validator preimages protocol
  arbitrator/jit/src/wavmio.rs
  validator/jit_machine.go
Labels: arbitrator, rust, s

#1303 Empty the gas cache before recording a batch posting report
  validator/stateless_block_validator.go
Labels: s

#1302 Fix formatting of block dates in validator
  validator/block_validator.go
Labels: s

#1306 Update markdown doc to v2.0.8
  docs/das/daserver-instructions.md
  docs/node-running/running-a-node.md
Labels: s

#1230 Handle feed reorgs
  arbnode/inbox_test.go
  arbnode/node.go
  arbnode/transaction_streamer.go
Labels: s

#1296 Adding a unit test for the util/containers/ queue.
  util/containers/queue.go
  util/containers/queue_test.go
Labels: s

#1295 Add an iterator and regular sync for storage service
  das/archiving_storage_service.go
  das/bigcache_storage_service.go
  das/cache_storage_to_das_adapter.go
  das/das.go
  das/db_storage_service.go
  das/iterable_storage_service.go
  das/key_utils.go
  das/local_file_storage_service.go
  das/memory_backed_storage_service.go
  das/read_limited.go
  das/redis_storage_service.go
  das/redundant_storage_service.go
  das/regular_sync_storage_test.go
  das/regularly_sync_storage.go
  das/s3_storage_service.go
Labels: AnyTrust, s

#1313 Lower staker make-assertion-interval in test node
  testnode-scripts/config.ts
Labels: s

#1315 Remove redundant reorg message that is inconsistent
  arbnode/transaction_streamer.go
Labels: s

#1316 Fix the type of the MaxMsgPerPoll config
  arbnode/seq_coordinator.go
Labels: s

#1318 Immediately try to post another batch if we just posted one
  arbnode/batch_poster.go
Labels: s

#1305 delay tips
  arbos/tx_processor.go
  system_tests/fees_test.go
Labels: s

#1327 Fix build strings
  Makefile
Labels: s

#1322 Add a batch poster option to limit the number of txs in the L1 mempool
  arbnode/dataposter/data_poster.go
Labels: s

#1317 Sync backends : Add option to enable syncFrom and syncTo storages
  arbnode/node.go
  das/archiving_storage_service.go
  das/bigcache_storage_service.go
  das/cache_storage_to_das_adapter.go
  das/das_test.go
  das/db_storage_service.go
  das/factory.go
  das/iterable_storage_service.go
  das/local_file_storage_service.go
  das/read_limited.go
  das/redis_storage_service.go
  das/redundant_storage_service.go
  das/regular_sync_storage_test.go
  das/rpc_test.go
  das/s3_storage_service.go
  system_tests/das_test.go
Labels: AnyTrust, s

#1331 adding-nownodes-provider
  docs/node-running/node-providers.md
Labels: docs, s

#1310 docker image for fuzzing
  Dockerfile
  fuzz.bash
Labels: s

#1294 Cleanup: update receiver names
  arbnode/inbox_reader.go
  arbos/incomingmessage.go
  arbos/storage/storage.go
  arbstate/das_reader.go
  das/aggregator.go
  das/chain_fetch_das.go
  statetransfer/jsondatareader.go
  statetransfer/memdatareader.go
  system_tests/arbtrace_test.go
  validator/eoa_validator_wallet.go
Labels: s

#1335 adding extra args for ws port
  docs/node-running/running-a-node.md
Labels: s

#1328 Use cf-connecting-ip for relay logging
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/clientmanager.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1336 docs: update DAC list
  docs/public-chains.md
Labels: s

#1338 docs: update to goerli arbiscan
  docs/useful-addresses.md
Labels: s

#1339 chore: use arbiscan api for nova and goerli
  contracts/hardhat.config.ts
Labels: s

#1270 Add option to download genesis state archive using IPFS url
  cmd/ipfshelper/ipfshelper.go
  cmd/ipfshelper/ipfshelper_test.go
  cmd/nitro/init.go
  go.mod
  go.sum
Labels: s

#1193 Fix ArbGasInfo L1 calldata gas price documentation
  contracts/src/precompiles/ArbGasInfo.sol
Labels: docs, s

#1346 Edits on docs precompiles
  docs/arbos/precompiles.md
Labels: s

#1329 Include failed connect register in metric counting
  wsbroadcastserver/clientmanager.go
Labels: s

#1349 Don't send feed cache if requested seqnum is too old
  broadcaster/sequencenumbercatchupbuffer.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1348 Do not connect to feed until node caught up to L1
  arbnode/inbox_reader.go
  arbnode/node.go
  broadcastclient/broadcastclient.go
  broadcastclients/broadcastclients.go
  util/stopwaiter/stopwaiter.go
  util/stopwaiter/stopwaiter_test.go
Labels: s

#1309 Optimize arbitrator some more
  arbitrator/Cargo.lock
  arbitrator/prover/Cargo.toml
  arbitrator/prover/src/machine.rs
  arbitrator/prover/src/main.rs
  arbitrator/prover/src/value.rs
  arbitrator/prover/test-cases/go/go.mod
  arbitrator/prover/test-cases/go/go.sum
Labels: arbitrator, s
