Repository OffchainLabs/nitro, pull requests merged in 2022-07, with the labels that each got.

#742 Add retries for upstream L1 connection for daserver
  arbnode/node.go
  das/aggregator.go
  das/das.go
  das/sign_after_store_das.go
Labels: AnyTrust, cla-signed

#741 Add geth metrics server to daserver
  cmd/daserver/daserver.go
  cmd/datool/datool.go
  das/dasrpc/dasRpcServer.go
  das/restful_server.go
Labels: AnyTrust, cla-signed

#748 Add solhint to contract ci
  .github/workflows/contract-tests.yml
Labels: contracts, CI, cla-signed

#751 Ignore solhint warnings when safe
  contracts/src/bridge/Inbox.sol
  contracts/src/libraries/IGasRefunder.sol
  contracts/src/rollup/RollupUserLogic.sol
  contracts/src/rollup/ValidatorWallet.sol
Labels: cla-signed

#744 Optionally make DAS fail early
  arbnode/node.go
  das/das.go
  das/dasrpc/rpc_test.go
  das/panic_wrapper.go
  system_tests/common_test.go
  system_tests/das_test.go
Labels: AnyTrust, cla-signed

#750 Allow watchtower validators to run without a key
  arbnode/api.go
  cmd/nitro/nitro.go
  validator/validator_wallet.go
Labels: node, cla-signed

#759 Add "Inside AnyTrust" doc
  docs/inside_anytrust.md
Labels: cla-signed

#761 L1 pricing formula fix edits
  .gitignore
  arbos/l1pricing/l1pricing.go
  system_tests/fees_test.go
Labels: cla-signed

#734 Distinguish missing inbox messages
  Dockerfile
  arbitrator/prover/src/machine.rs
  arbitrator/prover/src/main.rs
Labels: arbitrator, cla-signed

#766 Fix inbox backward check in RollupCore
  contracts/src/rollup/RollupCore.sol
Labels: contracts, cla-signed

#768 Check for gas limit overflow when parsing unsigned user tx
  arbos/incomingmessage.go
Labels: ArbOS, consensus, cla-signed

#755 Add flag to disable Sequencer DAS Store auto-fallback
  arbnode/batch_poster.go
Labels: AnyTrust, cla-signed

#771 Fix segment decompression in wrapped brotli
  arbstate/inbox.go
Labels: cla-signed

#743 Auto fetch mirror list without needing restart
  das/simple_das_reader_aggregator.go
Labels: AnyTrust, cla-signed

#757 Prevent deploy failure to set batch poster if owner is not deployer
  cmd/deploy/deploy.go
Labels: cla-signed

#774 Add node CLI flag to reorg to an old block for testing
  arbnode/node.go
Labels: cla-signed

#775 Version the poster fee mint destination to preserve old behavior
  arbos/tx_processor.go
Labels: cla-signed

#776 Fix GetL1GasPriceEstimate precompile
  precompiles/ArbGasInfo.go
Labels: cla-signed

#779 Disable bloom test when race mode enabled
  system_tests/bloom_test.go
Labels: cla-signed

#773 Improve retryable autoredeem gas checks
  arbos/tx_processor.go
Labels: cla-signed

#781 arbitrum db doesn't need freezer
  cmd/nitro/nitro.go
Labels: cla-signed

#782 Replace consensus v2 in dockerfile with consensus v2.1
  Dockerfile
Labels: cla-signed

#786 Error when validator repeatedly fails to act
  validator/staker.go
Labels: cla-signed

#785 Add gas refunder address to batch poster config
  arbnode/batch_poster.go
  arbnode/node.go
Labels: cla-signed

#787 Setup goerli rollup testnet defaults
  cmd/nitro/config_test.go
  cmd/nitro/nitro.go
Labels: cla-signed

#769 Convert remaining gofuzz fuzzers into native go fuzzing
  arbos/tx_processor.go
  arbstate/inbox_fuzz_test.go
  precompiles/ArbGasInfo.go
  system_tests/precompile_fuzz/precompile_fuzz.go
  system_tests/precompile_fuzz_test.go
  system_tests/state_fuzz_test.go
Labels: cla-signed

#772 Re-enable unsafe retryable entrypoints
  contracts/src/bridge/IInbox.sol
  contracts/src/bridge/Inbox.sol
Labels: contracts, cla-signed

#795 Update Nova default RPC and feed URLs
  cmd/nitro/nitro.go
Labels: cla-signed

#802 refactor: add dev natspec tag to comment
  contracts/src/node-interface/NodeInterface.sol
Labels: cla-signed

#807 Fix gosec ci lint
  arbnode/seq_coordinator.go
  das/dasrpc/dasRpcServer.go
  das/restful_server.go
  das/restful_server_list_test.go
Labels: CI, node, AnyTrust, cla-signed

#803 Panic if balance modification methods are called with negative amounts
  arbos/util/transfer.go
Labels: cla-signed

#799 Make `gasprice` opcode return 0 for `eth_call`'s with a zero gas price
  arbos/tx_processor.go
Labels: cla-signed

#789 Update dapp_migration.md
  docs/migration/dapp_migration.md
Labels: docs, cla-signed

#810 Represent deposit in tracing as mint to tx from account
  arbos/tx_processor.go
Labels: cla-signed

#801 Improve block-local gas rate limiting
  arbnode/sequencer.go
  arbos/block_processor.go
Labels: consensus, cla-signed

#812 Drop error when user tx uses too little gas (happens for deposits)
  arbos/block_processor.go
Labels: cla-signed

#790 Add per batch cost
  arbos/arbosState/arbosstate.go
  arbos/internal_tx.go
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing/l1pricing_test.go
  arbos/l1pricing_test.go
  contracts/src/precompiles/ArbGasInfo.sol
  contracts/src/precompiles/ArbOwner.sol
  precompiles/ArbGasInfo.go
  precompiles/ArbOwner.go
  precompiles/ArbOwner_test.go
Labels: ArbOS, consensus, cla-signed

#811 Add missing function to IOutbox
  contracts/src/bridge/IOutbox.sol
  contracts/src/bridge/Outbox.sol
  contracts/src/test-helpers/OutboxWithoutOptTester.sol
Labels: contracts, cla-signed

#814 Http server timeouts
  Makefile
  cmd/daserver/daserver.go
  cmd/dasrest/dasrest.go
  cmd/genericconf/server.go
  das/dasrpc/dasRpcServer.go
  das/dasrpc/rpc_test.go
  das/restful_server.go
  das/restful_server_test.go
  das/simple_das_reader_aggregator_test.go
  system_tests/das_test.go
Labels: cla-signed

#815 Fix network fee initialization
  arbos/arbosState/arbosstate.go
  arbos/internal_tx.go
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing/l1pricing_test.go
Labels: cla-signed

#791 Arbdebug pricing model v2
  arbnode/api.go
Labels: cla-signed

#745 syncing fallback storage service redesign
  .github/workflows/docker.yml
  arbnode/node.go
  das/sync_from_l1_chain.go
  das/syncing_fallback_storage.go
  system_tests/das_test.go
Labels: AnyTrust, cla-signed

#816 Fix validator if genesis was imported from classic
  validator/block_validator.go
  validator/validator_wallet.go
Labels: cla-signed

#739 Das merkle accumulator
  Dockerfile
  arbstate/das_reader.go
  arbstate/inbox.go
  cmd/datool/datool.go
  cmd/one-time-das-upgrade/upgrade.go
  cmd/replay/main.go
  contracts/src/bridge/SequencerInbox.sol
  das/aggregator.go
  das/aggregator_test.go
  das/archiving_storage_service.go
  das/archiving_storage_service_test.go
  das/bigcache_storage_service.go
  das/bigcache_storage_service_test.go
  das/cache_storage_to_das_adapter.go
  das/chain_fetch_das.go
  das/das.go
  das/das_test.go
  das/dasrpc/dasRpcClient.go
  das/dasrpc/dasRpcServer.go
  das/dasrpc/rpc_test.go
  das/dastree/dastree.go
  das/dastree/dastree_test.go
  das/db_storage_service.go
  das/fallback_storage_service.go
  das/fallback_storage_service_test.go
  das/local_file_storage_service.go
  das/memory_backed_storage_service.go
  das/panic_wrapper.go
  das/reader_aggregator_strategies_test.go
  das/redis_storage_service.go
  das/redis_storage_service_test.go
  das/redundant_simple_das_reader.go
  das/redundant_storage_service.go
  das/redundant_storage_test.go
  das/restful_client.go
  das/restful_server.go
  das/restful_server_test.go
  das/retry_wrapper.go
  das/s3_storage_service.go
  das/s3_storage_service_test.go
  das/sign_after_store_das.go
  das/simple_das_reader_aggregator.go
  das/simple_das_reader_aggregator_test.go
  das/storage_service.go
  das/store_signing.go
  das/syncing_fallback_storage.go
  das/timeout_wrapper.go
  das/util.go
  system_tests/common_test.go
  util/arbmath/bits.go
  util/arbmath/math.go
  util/pretty/pretty_printing.go
Labels: consensus, AnyTrust, cla-signed

#824 Download consensus v3 WAVM machine in Dockerfile
  Dockerfile
Labels: cla-signed

#823 fix init blocknumber offbyone
  arbnode/node.go
  cmd/nitro/nitro.go
  statetransfer/data.go
  statetransfer/interface.go
  statetransfer/jsondatareader.go
  statetransfer/memdatareader.go
Labels: cla-signed

#817 Init options
  arbnode/node.go
  cmd/nitro/config_test.go
  cmd/nitro/nitro.go
  go.mod
  go.sum
  statetransfer/data.go
  statetransfer/interface.go
  statetransfer/jsondatareader.go
  statetransfer/memdatareader.go
Labels: node, init, cla-signed

#829 Add consensus v3.1 WAVM machine to docker
  Dockerfile
Labels: cla-signed

#828 Support --node.dangerous.reorg-to-block with the block validator
  arbnode/node.go
  validator/block_validator.go
Labels: node, cla-signed

#831 Update dapp_migration.md
  docs/migration/dapp_migration.md
Labels: cla-signed

#834 Cleanup nodes in test harness
  arbnode/node.go
  system_tests/block_hash_test.go
  system_tests/block_validator_test.go
  system_tests/bloom_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/delayedinbox_test.go
  system_tests/delayedinboxlong_test.go
  system_tests/estimation_test.go
  system_tests/fees_test.go
  system_tests/full_challenge_impl_test.go
  system_tests/initialization_test.go
  system_tests/outbox_test.go
  system_tests/precompile_test.go
  system_tests/retryable_test.go
  system_tests/seq_coordinator_test.go
  system_tests/seq_whitelist_test.go
  system_tests/seqcompensation_test.go
  system_tests/seqfeed_test.go
  system_tests/seqinbox_test.go
  system_tests/staker_test.go
  system_tests/transfer_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: cla-signed

#819 In migration from classic, mint funds for retryable escrow accounts
  arbnode/node.go
  arbos/arbosState/initialization_test.go
  arbos/arbosState/initialize.go
  arbos/tx_processor.go
  system_tests/state_fuzz_test.go
Labels: cla-signed

#836 Fix random panic in DAS tests
  das/panic_wrapper.go
  validator/block_validator.go
Labels: cla-signed

#835 Upload WAVM machine as artifact from docker github action
  .github/workflows/docker.yml
  arbitrator/prover/src/main.rs
Labels: CI, cla-signed

#841 Fred patch
  contracts/src/bridge/IBridge.sol
  contracts/src/bridge/IInbox.sol
  contracts/src/rollup/RollupAdminLogic.sol
  contracts/src/state/GlobalState.sol
  contracts/src/test-helpers/OutboxWithoutOptTester.sol
Labels: cla-signed

#805 Add method to the rollup admin logic to import a migrated genesis block hash
  contracts/src/bridge/IBridge.sol
  contracts/src/bridge/IInbox.sol
  contracts/src/rollup/RollupAdminLogic.sol
  contracts/src/rollup/RollupCore.sol
  contracts/src/state/GlobalState.sol
  contracts/src/test-helpers/OutboxWithoutOptTester.sol
Labels: contracts, cla-signed

#844 Add rinkeby chain config
  cmd/nitro/nitro.go
Labels: cla-signed

#837 Fix division by zero in downloadInit and improve archive extraction
  cmd/nitro/nitro.go
Labels: node, cla-signed

#843 testnode: use dev-init
  testnode-scripts/config.ts
Labels: cla-signed

#847 Use current basefee to calculate submission fee if baseFee set to 0
  contracts/src/bridge/Inbox.sol
Labels: contracts, cla-signed

#849 Update dapp_migration.md
  docs/migration/dapp_migration.md
Labels: cla-signed

#855 Init empty
  cmd/nitro/nitro.go
Labels: cla-signed

#857 Install ca-certificates on slim to ensure functionality
  Dockerfile
Labels: cla-signed

#858 Fix redis test code coverage
  .github/workflows/ci.yml
Labels: cla-signed

#859 Sort retryables before import
  arbos/arbosState/initialize.go
Labels: cla-signed

#865 Add consensus v3.2 WAVM machine to docker
  Dockerfile
Labels: cla-signed

#866 Make TxLookupLimit configurable and set better defaults
  arbnode/inbox_test.go
  arbnode/node.go
  cmd/nitro/nitro.go
  system_tests/common_test.go
  system_tests/das_test.go
Labels: node, cla-signed

#853 sanitize markdown docs
  docs/arbos/ArbOS.md
  docs/arbos/CommonPrecompiles.md
  docs/arbos/Gas.md
  docs/arbos/Geth.md
  docs/arbos/Precompiles.md
  docs/arbos/e.png
  docs/intro.md
Labels: cla-signed

#869 Fix ArbGasInfo get price methods
  arbos/arbosState/arbosstate.go
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing/l1pricing_test.go
  precompiles/ArbGasInfo.go
Labels: ArbOS, consensus, cla-signed

#850 Return leafNum instead of sendHash from SendTxToL1
  precompiles/ArbSys.go
Labels: ArbOS, consensus, cla-signed

#863 Document ArbSys change in migration doc
  docs/migration/dapp_migration.md
Labels: docs, cla-signed

#839 Get rid of heartbeat L2 messages
  arbos/incomingmessage.go
Labels: ArbOS, consensus, cla-signed

#873 Disable heartbeat messages on August 8th
  arbos/incomingmessage.go
Labels: consensus

#874 Add consensus v4 WAVM machine to docker
  Dockerfile
Labels: cla-signed

#875 Don't panic when connected to a classic feed
  arbnode/transaction_streamer.go
  broadcastclient/broadcastclient.go
Labels: node, cla-signed
