Repository OffchainLabs/nitro, pull requests merged in 2022-12, with the labels that each got.

#1243 Resequence removed messages when a reorg occurs
  arbnode/node.go
  arbnode/sequencer.go
  arbnode/transaction_streamer.go
  system_tests/reorg_resequencing_test.go
Labels: s

#1351 Set new TxLookupLimit to better target 1 year
  arbnode/node.go
Labels: s

#1342 Add data availability (latest and old) check for daserver
  cmd/dataavailability/data_availability_check.go
  das/syncing_fallback_storage.go
Labels: AnyTrust, s

#1354 docs: update `TestCustomTokenL1.sol` link
  docs/asset-bridging.md
Labels: Type: Documentation, s

#1319 add logging to file option
  cmd/genericconf/config.go
  cmd/nitro/config_test.go
  cmd/nitro/filehandler_test.go
  cmd/nitro/nitro.go
  go.mod
  go.sum
Labels: s

#1370 Docs : Corrected the formatting for a missed header
  docs/tx-lifecycle.md
Labels: s

#1362 docs: fix typos and add admonition note blocks
  docs/tx-lifecycle.md
Labels: Type: Documentation, s

#1259 Fixed a typo
  docs/arbos/l2-to-l1-messaging.md
Labels: Type: Documentation, s

#1371 fix config fetching lambdas
  arbnode/node.go
Labels: s

#1373 Keep arbitrator host_call_hooks format for backwards compat
  arbitrator/prover/src/machine.rs
  arbitrator/prover/test-cases/go/go.sum
Labels: s

#1372 remove markdown docs
  README.md
  docs/arbitrum-ethereum-differences.md
  docs/arbos/arbos.md
  docs/arbos/common-precompiles.md
  docs/arbos/e.png
  docs/arbos/gas.md
  docs/arbos/geth.md
  docs/arbos/l1-pricing.md
  docs/arbos/l1-to-l2-messaging.md
  docs/arbos/l2-to-l1-messaging.md
  docs/arbos/precompiles.md
  docs/assertion-tree.md
  docs/assertionTree.png
  docs/asset-bridging.md
  docs/bridge_deposits.png
  docs/bridge_withdrawals.png
  docs/das/daserver-instructions.md
  docs/faqs/anytrust-vs-rollup.md
  docs/faqs/beta-status.md
  docs/faqs/how-fees.md
  docs/faqs/seq-or-val.md
  docs/faqs/the-merge.md
  docs/faqs/what-if-dispute.md
  docs/for-devs/cross-chain-messsaging.md
  docs/gatewayUML.svg
  docs/getting-started-devs.md
  docs/getting-started-users.md
  docs/inside-anytrust.md
  docs/inside-arbitrum-nitro/geth-sandwich.png
  docs/inside-arbitrum-nitro/inside-arbitrum-nitro.md
  docs/inside-arbitrum-nitro/seq-then-exec.png
  docs/intro/glossary.md
  docs/intro/intro.md
  docs/mainnet-beta.md
  docs/migration/dapp_migration.md
  docs/migration/state-migration.md
  docs/node-running/node-providers.md
  docs/node-running/running-a-classic-node.md
  docs/node-running/running-a-node.md
  docs/notice.md
  docs/proving/challenge-manager.md
  docs/proving/osp-assumptions.md
  docs/proving/wasm-to-wavm.md
  docs/proving/wavm-custom-opcodes.md
  docs/proving/wavm-floats.md
  docs/proving/wavm-modules.md
  docs/public-chains.md
  docs/sequencer.md
  docs/solidity-support.md
  docs/time.md
  docs/tx-lifecycle.md
  docs/useful-addresses.md
  docs/why-nitro.md
Labels: Type: Documentation, s

#1377 fix polling in FileHandler test
  cmd/nitro/filehandler_test.go
Labels: s

#1378 Add consensus v10 WASM machine to docker
  Dockerfile
Labels: s

#1375 revert: #1320 unsafe retryable caller
  contracts/src/bridge/Inbox.sol
  contracts/src/libraries/Constants.sol
Labels: contracts, s

#1220 chore: write attempt failed error on new line without erasing current…
  cmd/nitro/init.go
Labels: s

#1120 Setup test-node for developer usage
  docker-compose.yaml
  test-node.bash
  testnode-scripts/Dockerfile
  testnode-scripts/accounts.ts
  testnode-scripts/consts.ts
  testnode-scripts/ethcommands.ts
  testnode-scripts/index.ts
  testnode-scripts/redis.ts
Labels: s

#1325 Fix blockscout database URL to not include ?ssl=false
  docker-compose.yaml
Labels: s

#1382 Fix case for cloudflare http header
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1374 fix: add inbox gas limit validation
  contracts/src/bridge/Inbox.sol
  contracts/src/libraries/Error.sol
Labels: contracts, s

#1383 Improve feed broadcaster error logs and metrics
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/clientmanager.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1356 Update bridge enabled condition
  contracts/src/bridge/Bridge.sol
  contracts/src/mocks/BridgeStub.sol
Labels: contracts, s

#1359 Replace calldatasize() assembly block with msg.data.length
  contracts/src/libraries/IGasRefunder.sol
Labels: contracts, s

#1379 feat: uniswap unalised crosschain message
  contracts/src/bridge/Inbox.sol
  contracts/src/libraries/Constants.sol
  contracts/test/contract/arbRollup.spec.ts
Labels: contracts, s

#1323 support safe and finalized blocknumber
  arbnode/api.go
  arbnode/delayed_sequencer.go
  arbnode/inbox_reader.go
  arbnode/inbox_tracker.go
  arbnode/sync_monitor.go
  util/headerreader/header_reader.go
Labels: s

#1358 sequence delayed messages when acquiring lock
  arbnode/delayed_sequencer.go
  arbnode/seq_coordinator.go
  arbnode/sequencer.go
  system_tests/seq_pause_test.go
Labels: s

#1376 Fix wrong error for non batch to das failure
  arbnode/batch_poster.go
  das/aggregator.go
Labels: AnyTrust, s

#1386 Wasmer 3.1
  Dockerfile
  Makefile
  arbitrator/Cargo.lock
  arbitrator/Cargo.toml
  arbitrator/arbutil/Cargo.toml
  arbitrator/arbutil/src/color.rs
  arbitrator/arbutil/src/lib.rs
  arbitrator/jit/Cargo.toml
  arbitrator/jit/src/arbcompress.rs
  arbitrator/jit/src/gostack.rs
  arbitrator/jit/src/machine.rs
  arbitrator/jit/src/main.rs
  arbitrator/jit/src/runtime.rs
  arbitrator/jit/src/syscall.rs
  arbitrator/jit/src/test.rs
  arbitrator/jit/src/wavmio.rs
Labels: rust, s

#1389 Fix TestLiveNodeConfig creating a nitro.log file in cmd/nitro
  cmd/nitro/config_test.go
Labels: s

#1366 Anytrust ipfs node sync
  cmd/ipfshelper/ipfshelper.go
  cmd/nitro/init.go
  das/ipfs_storage_service.go
Labels: AnyTrust, s

#1390 deploy: delayed inbox upgrade
  contracts/src/bridge/Inbox.sol
  contracts/src/libraries/Constants.sol
  contracts/src/libraries/Error.sol
  contracts/test/contract/arbRollup.spec.ts
Labels: s

#1393 Fix CI failing due to lld-10 not existing
  .github/workflows/arbitrator-ci.yml
  .github/workflows/ci.yml
  arbitrator/jit/src/machine.rs
  arbitrator/jit/src/wavmio.rs
  arbitrator/prover/src/console.rs
  arbitrator/prover/src/machine.rs
  arbitrator/prover/src/value.rs
Labels: s

#1394 release: nitro-contracts 1.0.0
  contracts/package.json
Labels: contracts, s

#1395 header_reader: use finality data config
  util/headerreader/header_reader.go
Labels: s

#1396 Fix block hash in receipts in ws log subscription
  arbos/block_processor.go
  arbos/engine.go
  system_tests/log_subscription_test.go
Labels: s

#1401 fix panic with coordinator and no sequencer
  arbnode/seq_coordinator.go
Labels: s

#1388 Use new time-bounded histogram for timer metrics
  das/dasRpcServer.go
  das/restful_server.go
Labels: s

#1405 Use pointers for precompiles
  nodeInterface/virtual-contracts.go
  precompiles/precompile.go
  precompiles/wrapper.go
Labels: s

#1138 Add eslint and prettier to lint contract tests
  .github/workflows/contract-tests.yml
  contracts/.eslintrc.js
  contracts/.prettierignore
  contracts/.prettierrc
  contracts/.prettierrc.js
  contracts/.solhint.json
  contracts/README.md
  contracts/deploy/BridgeCreator.js
  contracts/deploy/BridgeStubCreator.js
  contracts/deploy/HashProofHelper.js
  contracts/deploy/InboxStubCreator.js
  contracts/deploy/OneStepProofEntryCreator.js
  contracts/deploy/OneStepProver0Creator.js
  contracts/deploy/OneStepProverHostIoCreator.js
  contracts/deploy/OneStepProverMathCreator.js
  contracts/deploy/OneStepProverMemoryCreator.js
  contracts/deploy/SequencerInbox.js
  contracts/deploy/SequencerInboxStubCreator.js
  contracts/deploy/ValueArrayTesterCreator.js
  contracts/hardhat.config.ts
  contracts/hardhat.prod-config.js
  contracts/package.json
  contracts/test/contract/arbRollup.spec.ts
  contracts/test/contract/common/challengeLib.ts
  contracts/test/contract/common/globalStateLib.ts
  contracts/test/contract/common/rolluplib.ts
  contracts/test/contract/cryptographyPrimitives.spec.ts
  contracts/test/contract/outbox/withdraw-testcase.json
  contracts/test/contract/outboxOptimisation.spec.ts
  contracts/test/contract/sequencerInboxForceInclude.spec.ts
  contracts/test/contract/utils.ts
  contracts/test/contract/validatorWallet.spec.ts
  contracts/test/prover/hash-proofs.ts
  contracts/test/prover/one-step-proof.ts
  contracts/test/prover/value-arrays.ts
  contracts/tsconfig.json
  contracts/yarn.lock
Labels: contracts, testing, s
