Repository OffchainLabs/nitro, pull requests merged in 2022-09, with the labels that each got.

#1058 Improve data cost estimation when full tx hurts compression ratio
  arbos/l1pricing/l1pricing.go
  arbos/l1pricing/l1pricing_test.go
  nodeInterface/NodeInterface.go
  precompiles/ArbGasInfo.go
  util/arbmath/bips.go
Labels: node, s

#1060 adding the nitro seed db url to the docs
  docs/public-chains.md
Labels: s

#1061 Update docs to latest node release of v2.0.1
  docs/node-running/running-a-node.md
Labels: s

#1059 Minor doc update for forwarding classic requests
  docs/node-running/running-a-node.md
Labels: s

#1053 update dapp migration docs; make past tense, copy edits
  docs/migration/dapp_migration.md
Labels: docs, s

#1064 Fix delayed messages being replayed causing a sequencer batch reorg
  arbnode/delayed_seq_reorg_test.go
  arbnode/inbox_reader.go
  arbnode/inbox_tracker.go
Labels: node, s

#1066 add chainstack to 3rd party node provider docs
  docs/node-running/node-providers.md
Labels: docs, s

#1067 clarify L1/L2 fee behavior
  docs/arbos/gas.md
  docs/faqs/how-fees.md
  docs/why-nitro.md
Labels: docs, s

#1065 Method for estimating just l1 costs
  arbos/l1pricing/l1pricing.go
  contracts/src/node-interface/NodeInterface.sol
  nodeInterface/NodeInterface.go
Labels: s

#1068 Add instructions on how to do graceful docker shutdown
  docs/node-running/running-a-classic-node.md
  docs/node-running/running-a-node.md
Labels: s

#990 Allow build version to be specified by environment variables
  .nitro-tag.txt
  Dockerfile
  Makefile
  arbos/util/retryable_encoding_test.go
  broadcaster/sequencenumbercatchupbuffer.go
  cmd/conf/database.go
  cmd/daserver/daserver.go
  cmd/genericconf/getversion17.go
  cmd/genericconf/getversion18.go
  cmd/nitro/init.go
  cmd/nitro/nitro.go
  cmd/relay/relay.go
  cmd/util/configuration.go
  das/rpc_test.go
  das/syncing_fallback_storage.go
  system_tests/das_test.go
  util/headerreader/header_reader.go
  util/normalizeGas.go
Labels: cla-signed, s

#1070 Update whitepaper
  docs/Nitro-whitepaper.pdf
Labels: docs, s

#1071 Typo fix
  docs/assertion-tree.md
  docs/sequencer.md
  docs/time.md
Labels: docs, s

#1073 update wp - cancelled retryables
  docs/Nitro-whitepaper.pdf
Labels: docs, s

#1074 Add version to web3_clientVersion response
  cmd/nitro/nitro.go
Labels: s

#1075 Explicitly require `--metrics-server.addr` if `--metrics` set
  cmd/daserver/daserver.go
Labels: s

#1077 Fix segfault when blockValidator not present
  validator/staker.go
Labels: s

#1078 Bump nitro-node to v2.0.2 in Docs
  docs/node-running/running-a-node.md
Labels: docs, s

#1080 Don't wait for the next block interval if no block was produced
  arbnode/sequencer.go
Labels: s

#1081 Add safety checks that we aren't accidentally accepting an internal tx
  arbnode/sequencer.go
  arbos/incomingmessage.go
Labels: s

#1085 Remove link to devnet page
  README.md
Labels: s

#1087 Handle arm64 build
  Dockerfile
Labels: s

#1091 add nova one step proof addresses, fix arb1 challenge manager address (docs)
  docs/useful-addresses.md
Labels: docs, s

#894 Improve TxPreChecker
  arbnode/node.go
  arbnode/sequencer.go
  arbnode/tx_pre_checker.go
  arbos/block_processor.go
  system_tests/seq_coordinator_test.go
Labels: node, cla-signed, s

#1092 update chainstack node support (docs)
  docs/node-running/node-providers.md
Labels: docs, s

#1094 Make test-node.bash portable
  test-node.bash
Labels: s

#958 simple redis lock for batch poster
  .github/workflows/ci.yml
  Makefile
  arbnode/batch_poster.go
  arbnode/dataposter/data_poster.go
  arbnode/dataposter/redis_storage.go
  arbnode/seq_coordinator.go
  arbnode/seq_coordinator_atomic_test.go
  arbnode/simple_redis_lock.go
  arbnode/simple_redis_lock_test.go
  arbnode/transaction_streamer.go
  cmd/seq-coordinator-invalidate/seq-coordinator-invalidate.go
  das/redis_storage_service.go
  docker-compose.yaml
  system_tests/batch_poster_test.go
  system_tests/redis_test.go
  system_tests/seq_coordinator_test.go
  test-node.bash
  testnode-scripts/config.ts
  testnode-scripts/ethcommands.ts
  testnode-scripts/index.ts
  util/redisutil/redisutil.go
  util/redisutil/test_no_redis.go
  util/redisutil/test_redis.go
Labels: cla-signed, s

#980 sync_monitor
  arbnode/batch_poster.go
  arbnode/node.go
  arbnode/seq_coordinator.go
  arbnode/sync_monitor.go
  arbnode/transaction_streamer.go
  system_tests/batch_poster_test.go
  system_tests/seq_coordinator_test.go
Labels: cla-signed, s

#1079 JIT validator
  Dockerfile
  Makefile
  arbitrator/Cargo.lock
  arbitrator/Cargo.toml
  arbitrator/jit/.gitignore
  arbitrator/jit/Cargo.lock
  arbitrator/jit/Cargo.toml
  arbitrator/jit/build.rs
  arbitrator/jit/programs/print/main.go
  arbitrator/jit/programs/pure/main.wat
  arbitrator/jit/programs/time/main.go
  arbitrator/jit/src/arbcompress.rs
  arbitrator/jit/src/color.rs
  arbitrator/jit/src/gostack.rs
  arbitrator/jit/src/machine.rs
  arbitrator/jit/src/main.rs
  arbitrator/jit/src/runtime.rs
  arbitrator/jit/src/socket.rs
  arbitrator/jit/src/syscall.rs
  arbitrator/jit/src/test.rs
  arbitrator/jit/src/wavmio.rs
  arbitrator/prover/src/machine.rs
  arbitrator/wasm-libraries/go-abi/src/lib.rs
  arbnode/api.go
  arbnode/node.go
  broadcastclient/broadcastclient.go
  cmd/nitro/nitro.go
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/full_challenge_impl_test.go
  system_tests/seqinbox_test.go
  system_tests/staker_test.go
  validator/block_validator.go
  validator/challenge_manager.go
  validator/jit_machine.go
  validator/nitro_machine.go
  validator/stateless_block_validator.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1099 Fix crash in RenderRPCError with empty revert data
  arbstate/geth-hook.go
Labels: s

#1100 Recover from a sequencer crash when creating blocks
  arbnode/sequencer.go
Labels: s

#1102 Use github actions cache v3
  .github/workflows/ci.yml
Labels: CI, s

#1098 Update docs to note latest nitro version 2.0.3
  docs/node-running/running-a-node.md
Labels: s

#1097 Add gas refunder support to validator config
  validator/staker.go
  validator/validator_wallet.go
Labels: s

#1105 add merge faq
  docs/faqs/the-merge.md
Labels: docs, s

#1107 Simplify sequencer forwarding to not use queue
  arbnode/sequencer.go
Labels: s

#1108 wait for snapshot generation if init.then-quit
  cmd/nitro/init.go
Labels: s

#1109 Download replay binary for wasm machines in docker
  .dockerignore
  Dockerfile
  testnode-scripts/download-machine.sh
Labels: s

#1110 Find docker machines
  arbnode/node.go
Labels: s

#1113 Use JIT validator by default
  cmd/nitro/nitro.go
Labels: s

#986 Have sequencer sign each feed message and nodes validate signatures
  .github/workflows/arbitrator-ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker.yml
  Dockerfile
  arbitrator/prover/test-cases/go/go.mod
  arbitrator/prover/test-cases/go/go.sum
  arbnode/batch_poster.go
  arbnode/node.go
  arbnode/seq_coordinator_atomic_test.go
  arbnode/transaction_streamer.go
  arbos/incomingmessage.go
  arbstate/inbox.go
  broadcastclient/broadcastclient.go
  broadcastclient/broadcastclient_test.go
  broadcaster/broadcaster.go
  broadcaster/broadcaster_serialization_test.go
  broadcaster/broadcaster_test.go
  broadcaster/sequencenumbercatchupbuffer.go
  broadcaster/sequencenumbercatchupbuffer_test.go
  cmd/datool/datool.go
  cmd/nitro/nitro.go
  cmd/relay/relay.go
  cmd/util/keystore.go
  das/aggregator.go
  das/extra_signature_checker_test.go
  das/factory.go
  das/sign_after_store_das.go
  das/store_signing.go
  das/store_signing_test.go
  relay/relay.go
  system_tests/das_test.go
  system_tests/seqfeed_test.go
  util/contracts/batch_poster_verifier.go
  util/signature/datasigner.go
  util/signature/verifier.go
  util/signature/verifier_test.go
  validator/block_validator.go
  validator/challenge_manager.go
  validator/stateless_block_validator.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: cla-signed, s

#1104 add additional gas info to docs
  docs/arbos/gas.md
  docs/arbos/l1-pricing.md
Labels: docs, s

#1103 Fix some spelling errors
  contracts/src/bridge/IOutbox.sol
  contracts/src/precompiles/ArbSys.sol
Labels: contracts, s

#1116 Allow enabling sequencer without delayed sequencer
  arbnode/node.go
Labels: node, s

#1119 Improve two's complement testing and fix overflow/underflow edge cases
  arbos/burn/burn.go
  arbos/storage/storage.go
  arbos/storage/storage_test.go
  precompiles/context.go
Labels: s

#1026 Prevent L2 replay attack when L1 forked
  contracts/src/bridge/IInbox.sol
  contracts/src/bridge/Inbox.sol
  contracts/src/libraries/Error.sol
  contracts/src/mocks/InboxStub.sol
  contracts/test/contract/sequencerInboxForceInclude.spec.ts
Labels: contracts, s, fork

#1025 Allow progression when all validators are gone
  contracts/src/rollup/IRollupLogic.sol
  contracts/src/rollup/RollupUserLogic.sol
  contracts/test/contract/arbRollup.spec.ts
Labels: contracts, s, fork

#1057 more hot reloadable config options and on-config-reload hook
  arbnode/batch_poster.go
  arbnode/delayed_sequencer.go
  arbnode/inbox_reader.go
  arbnode/node.go
  arbnode/sequencer.go
  broadcastclient/broadcastclient.go
  broadcastclient/broadcastclient_test.go
  broadcaster/broadcaster.go
  broadcaster/broadcaster_test.go
  cmd/deploy/deploy.go
  cmd/nitro/nitro.go
  relay/relay.go
  system_tests/common_test.go
  system_tests/das_test.go
  util/headerreader/header_reader.go
  validator/block_validator.go
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/clientmanager.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1124 use cranelift by default
  validator/block_validator.go
Labels: s

#877 Add modular data poster to allow batch poster to queue up txs
  .github/workflows/ci.yml
  Makefile
  arbnode/batch_poster.go
  arbnode/dataposter/data_poster.go
  arbnode/dataposter/redis_storage.go
  arbnode/dataposter/slice_storage.go
  arbnode/inbox_reader.go
  arbnode/inbox_tracker.go
  arbnode/node.go
  arbnode/seq_coordinator.go
  arbnode/seq_coordinator_atomic_test.go
  arbnode/simple_redis_lock.go
  arbnode/simple_redis_lock_test.go
  arbnode/sync_monitor.go
  arbnode/transaction_streamer.go
  cmd/nitro/nitro.go
  cmd/seq-coordinator-invalidate/seq-coordinator-invalidate.go
  das/redis_storage_service.go
  docker-compose.yaml
  system_tests/batch_poster_test.go
  system_tests/full_challenge_impl_test.go
  system_tests/redis_test.go
  system_tests/seq_coordinator_test.go
  test-node.bash
  testnode-scripts/config.ts
  testnode-scripts/ethcommands.ts
  testnode-scripts/index.ts
  util/redisutil/redisutil.go
  util/redisutil/test_no_redis.go
  util/redisutil/test_redis.go
  util/simple_hmac/simple_hmac.go
Labels: node, cla-signed, s

#1123 update node docker image to v2.0.4
  docs/node-running/running-a-node.md
Labels: s

#994 Handle L1 fork by chainid change
  contracts/src/bridge/IInbox.sol
  contracts/src/bridge/ISequencerInbox.sol
  contracts/src/bridge/Inbox.sol
  contracts/src/bridge/SequencerInbox.sol
  contracts/src/libraries/Error.sol
  contracts/src/mocks/InboxStub.sol
  contracts/src/rollup/IRollupCore.sol
  contracts/src/rollup/IRollupLogic.sol
  contracts/src/rollup/RollupAdminLogic.sol
  contracts/src/rollup/RollupCore.sol
  contracts/src/rollup/RollupUserLogic.sol
  contracts/test/contract/arbRollup.spec.ts
  contracts/test/contract/sequencerInboxForceInclude.spec.ts
  contracts/test/storage/RollupAdminLogic.dot
  contracts/test/storage/RollupCore.dot
  contracts/test/storage/RollupUserLogic.dot
Labels: contracts, s, fork

#1131 Add consensus v7 WASM machine to docker
  Dockerfile
Labels: s

#1128 Remove non-prom allowed chars from das agg metrics
  das/aggregator.go
  das/rpc_aggregator.go
Labels: AnyTrust, s

#1118 Add basic feed metrics for server and client
  broadcastclient/broadcastclient.go
  broadcaster/sequencenumbercatchupbuffer.go
  cmd/relay/relay.go
  wsbroadcastserver/clientmanager.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1129 post-merge docs updates
  docs/arbos/gas.md
  docs/arbos/geth.md
  docs/faqs/the-merge.md
  docs/faqs/what-if-dispute.md
  docs/intro/glossary.md
  docs/intro/intro.md
Labels: docs, s

#1133 Add `arb_sequencer_active` metric
  arbnode/seq_coordinator.go
Labels: s

#1135 Fix math test fluke in CI
  util/arbmath/math_test.go
Labels: s

#1137 Add startup message when validator
  arbnode/node.go
Labels: s

#1140 Update docs to note latest nitro version 2.0.5
  docs/node-running/running-a-node.md
Labels: s

#1143 Fix metric name
  broadcaster/sequencenumbercatchupbuffer.go
Labels: s

#1145 Listen for JIT on IPv4
  validator/jit_machine.go
Labels: s

#1144 If running validator, require archive mode
  cmd/nitro/nitro.go
Labels: s

#1139 update inside arbitrum: validation
  docs/inside-arbitrum-nitro/inside-arbitrum-nitro.md
Labels: docs, s

#1150 Only listen on localhost for the jit validator
  validator/jit_machine.go
Labels: s

#1151 Allow validator smart contract wallet to be specified
  arbnode/node.go
  system_tests/staker_test.go
  validator/staker.go
  validator/validator_wallet.go
Labels: s

#1148 update readme
  README.md
Labels: docs, s

#1142 Fix code to always use go-ethereum log module for consistency
  arbos/arbosState/arbosstate.go
  arbos/arbosState/initialize.go
  precompiles/context.go
Labels: s

#1152 Fix `ClientConnection.StopAndWait`
  broadcaster/sequencenumbercatchupbuffer.go
  wsbroadcastserver/clientconnection.go
Labels: s

#1141 Add instructions on how to run validator node in watchtower mode
  docs/node-running/running-a-node.md
Labels: docs, s

#1160 Fix staker challenge tests
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/seqfeed_test.go
  system_tests/staker_test.go
Labels: s

#1165 Add additional logging when estimating gas for batch fails
  arbnode/batch_poster.go
Labels: s

#1156 add ipc rpc support
  cmd/genericconf/server.go
  cmd/nitro/nitro.go
  system_tests/batch_poster_test.go
  system_tests/block_validator_test.go
  system_tests/common_test.go
  system_tests/fees_test.go
  system_tests/ipc_test.go
  system_tests/seqfeed_test.go
  system_tests/seqinbox_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: s

#1169 no live sequencer log should be error
  arbnode/redis_coordinator.go
Labels: s

#1168 Add sequencer backlog gauge metric
  arbnode/sequencer.go
Labels: s

#1170 Fix batch poster testForOverflow
  arbnode/batch_poster.go
Labels: s

#1172 Prompt use to upgrade node if unrecognized arbos version
  arbos/arbosState/arbosstate.go
Labels: s

#1174 Fix test mutating default stack config
  system_tests/common_test.go
Labels: s

#1159 Ensure feed ping gets sent regardless of other traffic
  arbnode/sync_monitor.go
  arbnode/transaction_streamer.go
  broadcaster/sequencenumbercatchupbuffer.go
  cmd/relay/config_test.go
  cmd/relay/relay.go
  relay/relay.go
  system_tests/seqfeed_test.go
  util/sharedmetrics/sharedmetrics.go
  wsbroadcastserver/clientmanager.go
Labels: s

#1181 Validator shouldn't require deprecated parameter
  cmd/nitro/nitro.go
Labels: s

#1182 Update documentation to `node.caching.archive` instead of deprecated
  cmd/nitro/nitro.go
  docs/node-running/running-a-node.md
Labels: s

#1184 Fix err print in start tx hook
  arbos/tx_processor.go
Labels: s

#1179 Fix jit validator shutdown cancellation
  validator/block_validator.go
  validator/jit_machine.go
  validator/stateless_block_validator.go
Labels: s

#1166 life cycle controlled by node
  arbnode/node.go
  cmd/nitro/nitro.go
  system_tests/aliasing_test.go
  system_tests/batch_poster_test.go
  system_tests/block_hash_test.go
  system_tests/block_validator_test.go
  system_tests/bloom_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/delayedinbox_test.go
  system_tests/delayedinboxlong_test.go
  system_tests/estimation_test.go
  system_tests/fees_test.go
  system_tests/infra_fee_test.go
  system_tests/initialization_test.go
  system_tests/ipc_test.go
  system_tests/outbox_test.go
  system_tests/precompile_test.go
  system_tests/retryable_test.go
  system_tests/seq_coordinator_test.go
  system_tests/seq_reject_test.go
  system_tests/seq_whitelist_test.go
  system_tests/seqcompensation_test.go
  system_tests/seqfeed_test.go
  system_tests/seqinbox_test.go
  system_tests/staker_test.go
  system_tests/transfer_test.go
  system_tests/twonodes_test.go
  system_tests/twonodeslong_test.go
Labels: s

#1186 Fix arbitrator CI due to unused value
  arbitrator/prover/src/lib.rs
Labels: arbitrator, s

#1183 Move RedisCoordinator into redisutil
  arbnode/seq_coordinator.go
  arbnode/seq_coordinator_atomic_test.go
  system_tests/seq_coordinator_test.go
  util/redisutil/redis_coordinator.go
Labels: s

#1161 Allow for an EOA validator wallet
  arbnode/node.go
  cmd/nitro/nitro.go
  system_tests/staker_test.go
  validator/builder_backend.go
  validator/eoa_validator_wallet.go
  validator/l1_validator.go
  validator/staker.go
  validator/validator_wallet.go
Labels: s

#1190 Fix typo in metric name
  util/sharedmetrics/sharedmetrics.go
Labels: s

#1194 Add `stopwaiter.CallIterativelyWithTrigger`
  util/stopwaiter/stopwaiter.go
Labels: s

#1195 dont assume validator succeeded
  validator/block_validator.go
Labels: s

#1163 Orderly sequencer shutdown
  arbnode/node.go
  arbnode/seq_coordinator.go
  arbnode/sequencer.go
  util/redisutil/redis_coordinator.go
  util/stopwaiter/stopwaiter.go
Labels: s

#1196 Improve validator logging around invalid assertions and whitelisting
  arbnode/node.go
  validator/l1_validator.go
  validator/staker.go
Labels: s

#1192 Jit path
  validator/jit_machine.go
Labels: s

#1197 Remove rpc getbyhash metrics, duration is ns
  docs/das/daserver-instructions.md
Labels: s

#1199 Don't write canceled validation blocks to disk
  validator/block_validator.go
Labels: s

#1200 Instead of panicking, make a fatal error when node is out of date
  arbnode/inbox_test.go
  arbnode/node.go
  arbnode/transaction_streamer.go
  arbos/arbosState/arbosstate.go
  arbos/block_processor.go
  arbos/internal_tx.go
  arbos/tx_processor.go
  cmd/nitro/nitro.go
Labels: s

#1198 Allow running a watchtower validator without archive mode enabled
  cmd/nitro/nitro.go
Labels: s

#1162 Updated Readme with clear details and links to resources
  README.md
Labels: docs, s

#1201 Handle unexpected relay input on connect
  broadcaster/broadcaster.go
  broadcaster/sequencenumbercatchupbuffer.go
  broadcaster/sequencenumbercatchupbuffer_test.go
  wsbroadcastserver/clientmanager.go
Labels: s
