Repository OffchainLabs/nitro, pull requests merged in 2023-01, with the labels that each got.

#1387 Validation service: initial preparations
  arbnode/api.go
  arbnode/inbox_tracker.go
  arbnode/node.go
  arbnode/transaction_streamer.go
  cmd/nitro/nitro.go
  nodeInterface/NodeInterface.go
  staker/assertion.go
  staker/block_challenge_backend.go
  staker/block_validator.go
  staker/block_validator_schema.go
  staker/builder_backend.go
  staker/challenge_manager.go
  staker/challenge_test.go
  staker/common_test.go
  staker/eoa_validator_wallet.go
  staker/l1_validator.go
  staker/rollup_watcher.go
  staker/staker.go
  staker/stateless_block_validator.go
  staker/validator_wallet.go
  system_tests/full_challenge_impl_test.go
  system_tests/staker_test.go
  validator/execution_challenge_backend.go
  validator/execution_state.go
  validator/jit_machine.go
  validator/machine.go
  validator/mock_machine.go
  validator/nitro_machine.go
  validator/validation_entry.go
  validator/validator_spawner.go
Labels: s

#1406 Make the trie dirty cache size configurable
  arbnode/node.go
Labels: s

#1409 chore: update nitro node version to v2.0.9-51f9452-dev
  test-node.bash
Labels: s

#1411 use snapshot-restore-gas-limit
  arbnode/node.go
Labels: s

#1416 Fix inbox reader caught up tracking if already caught up
  arbnode/inbox_reader.go
Labels: s

#1420 syncmap shows l1 state
  arbnode/sync_monitor.go
  util/headerreader/header_reader.go
Labels: s

#1422 feed client metric should be microseconds instead of nanoseconds
  wsbroadcastserver/clientmanager.go
Labels: s

#1403 chore: pin sdk to v3.0.0 in test node script
  testnode-tokenbridge/Dockerfile
Labels: s

#1425 Update formula for max fee calculation for batch posting
  arbnode/dataposter/data_poster.go
  util/arbmath/math.go
Labels: s

#1418 Add a cache of txs which failed due to nonce too high
  arbnode/sequencer.go
  arbnode/tx_pre_checker.go
  go.mod
  go.sum
  system_tests/common_test.go
  system_tests/seq_nonce_test.go
  system_tests/test_info.go
  util/containers/lru.go
Labels: s

#1429 Upgdate go.mod in prover test case
  arbitrator/prover/test-cases/go/go.sum
Labels: s

#1424 Add isSequencer mapping to SequencerInbox
  contracts/src/bridge/ISequencerInbox.sol
  contracts/src/bridge/SequencerInbox.sol
  contracts/test/storage/SequencerInbox.dot
Labels: contracts, s

#1433 Use IsSequencer mapping
  arbnode/node.go
  arbnode/seq_coordinator.go
  broadcastclient/broadcastclient.go
  broadcastclient/broadcastclient_test.go
  broadcastclients/broadcastclients.go
  das/aggregator.go
  das/sign_after_store_das.go
  util/contracts/address_verifier.go
  util/signature/sign_verify.go
  util/signature/verifier.go
  util/signature/verifier_test.go
Labels: s

#1273 Add Ability to Post Shard Blob Txs for Sequencer Batches
  arbnode/batch_poster.go
  arbnode/batch_poster_test.go
  arbnode/dataposter/data_poster.go
  arbnode/dataposter/data_poster_test.go
  cryptography/kzg/kzg.go
  go.mod
  go.sum
  system_tests/precompile_fuzz_test.go
Labels: s

#1437 Improve logging when we fail to find a sequencer batch
  arbnode/inbox_reader.go
Labels: s

#1438 Don't use sequencing hooks when resequencing reorg'd messages
  arbnode/sequencer.go
  arbnode/transaction_streamer.go
  arbos/block_processor.go
Labels: s

#1439 Improve logging when error loading wallet from file
  cmd/nitro/nitro.go
Labels: s

#1402 Feed compression
  arbnode/node.go
  broadcastclient/broadcastclient.go
  broadcastclient/broadcastclient_test.go
  broadcastclients/broadcastclients.go
  relay/relay.go
  wsbroadcastserver/clientconnection.go
  wsbroadcastserver/clientmanager.go
  wsbroadcastserver/dictionary.go
  wsbroadcastserver/utils.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1443 only send record from single thread
  staker/block_validator.go
  system_tests/block_validator_test.go
Labels: s

#1423 Simplify DAS Orchestration and Abstraction
  arbnode/node.go
  arbstate/das_reader.go
  cmd/daserver/daserver.go
  cmd/dataavailability/data_availability_check.go
  das/aggregator_test.go
  das/archiving_storage_service.go
  das/archiving_storage_service_test.go
  das/cache_storage_to_das_adapter.go
  das/chain_fetch_das.go
  das/das.go
  das/dasRpcServer.go
  das/das_test.go
  das/factory.go
  das/fallback_storage_service.go
  das/fallback_storage_service_test.go
  das/redundant_simple_das_reader.go
  das/restful_server.go
  das/restful_server_test.go
  das/retry_wrapper.go
  das/rpc_test.go
  das/sign_after_store_das_writer.go
  das/syncing_fallback_storage.go
  system_tests/common_test.go
  system_tests/das_test.go
Labels: s

#1444 Fix batchMeta cache invalidation on reorg
  arbnode/inbox_tracker.go
  system_tests/meaningless_reorg_test.go
Labels: s

#1436 Validate latest batch even if chain isn't progressing
  staker/block_validator.go
Labels: s

#1446 Improve feed reorg handling in transaction streamer
  arbnode/transaction_streamer.go
Labels: s

#1450 Log ErrRetrySequencer and if sequencing takes too long
  arbnode/sequencer.go
Labels: s

#1447 Add error context everywhere in the validator code
  staker/challenge_manager.go
  staker/l1_validator.go
  staker/staker.go
Labels: s

#1449 Format l1Timestamp and localTimestamp in sequencer error
  arbnode/sequencer.go
Labels: s

#1451 Fix the default wsbroadcastserver RequireCompression value
  wsbroadcastserver/wsbroadcastserver.go
Labels: s

#1454 Harden the batch poster
  arbnode/batch_poster.go
  arbnode/dataposter/data_poster.go
  arbnode/dataposter/redis_storage.go
Labels: s

#1457 Fix batch poster failing to estimate gas on restart
  arbnode/batch_poster.go
  arbnode/dataposter/data_poster.go
  arbnode/node.go
  system_tests/batch_poster_test.go
Labels: s

#1392 Fix finalizer synchronization for Arbitrator machines
  validator/machine.go
  validator/validator_spawner.go
Labels: s

#1460 Pin rustc 1.66.1 in CI
  .github/workflows/arbitrator-ci.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: Type: CI, s

#1464 advance l1 in fee tests
  system_tests/fees_test.go
Labels: s

#1465 Update docker version used by test-node.sh
  test-node.bash
Labels: s

#1468 Use a custom header for our websocket compression
  wsbroadcastserver/utils.go
Labels: s

#1459 [Config Changes] Rework wsbroadcastserver client IO deadlines
  wsbroadcastserver/utils.go
  wsbroadcastserver/wsbroadcastserver.go
Labels: s
