Repository OffchainLabs/nitro, pull requests merged in 2024-12, with the labels that each got.

#2813 Update AEP link
  LICENSE.md
  README.md
Labels: s, design-approved

#2815 Fix StopOnly followed by StopAndWait
  util/stopwaiter/stopwaiter.go
  util/stopwaiter/stopwaiter_test.go
Labels: s, design-approved

#2729 refactor: using maps.Clone
  das/reader_aggregator_strategies.go
Labels: s, design-approved

#2558 Don’t print redis errors when sequencer coordinator enabled node is syncing
  arbnode/seq_coordinator.go
Labels: s, design-approved

#2738 [NIT-2834] Add redis sentinel support
  util/redisutil/redisutil.go
Labels: s, design-approved

#2761 [NIT-2879] Add support for standard genesis.json format
  cmd/conf/init.go
  cmd/nitro/init.go
Labels: s, design-approved

#2795 Fix das store related error logging
  das/aggregator.go
Labels: s, design-approved

#2582 [Config Change] Start node only after the block containing rollup creation tx has been finalized (if supported)
  cmd/nitro/nitro.go
Labels: s, design-approved

#2788 Add early timeboost submission grace period
  cmd/nitro/nitro.go
  execution/gethexec/express_lane_service.go
  execution/gethexec/express_lane_service_test.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
  timeboost/ticker.go
Labels: s

#2808 Use EIP712 signing scheme for bids
  timeboost/bid_cache.go
  timeboost/bid_validator.go
  timeboost/bid_validator_test.go
  timeboost/bidder_client.go
  timeboost/types.go
Labels: s

#2758 Modify the batch poster to support the delay buffer feature
  arbnode/batch_poster.go
  arbnode/delay_buffer.go
  system_tests/batch_poster_test.go
  system_tests/common_test.go
Labels: s, design-approved

#2685 chore: add missing precompiles comments based on interfaces
  precompiles/ArbAggregator.go
  precompiles/ArbDebug.go
  precompiles/ArbOwner.go
  precompiles/ArbRetryableTx.go
Labels: s, design-approved

#2830 Deduplicate arbitrator RustBytes types
  arbitrator/prover/src/lib.rs
  arbitrator/stylus/src/evm_api.rs
  arbitrator/stylus/src/lib.rs
  arbos/programs/native.go
  validator/server_arb/machine.go
Labels: arbitrator, s, design-approved

#2829 Remove probably leftover println
  validator/server_arb/validator_spawner.go
Labels: s, design-approved

#2828 Add bold stake token to sepolia chain info
  cmd/chaininfo/arbitrum_chain_info.json
Labels: s, design-approved

#2651 Fix the delayed sequencer missing messages in tests
  arbnode/delayed_sequencer.go
  system_tests/block_validator_test.go
Labels: s, design-approved

#2841 Refactor RoundTimingInfo, fix auctionCloseTicker
  execution/gethexec/express_lane_service.go
  execution/gethexec/express_lane_service_test.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
  timeboost/auctioneer.go
  timeboost/bid_validator.go
  timeboost/bid_validator_test.go
  timeboost/bidder_client.go
  timeboost/roundtiminginfo.go
  timeboost/ticker.go
  timeboost/ticker_test.go
Labels: s

#2833 Timeboost-test: Express lane control transfer
  system_tests/timeboost_test.go
Labels: s

#2553 Add prestateTracer system_tests
  system_tests/debugapi_test.go
Labels: s, design-approved

#2843 Bump default message pruner min batches left to 1k
  arbnode/message_pruner.go
Labels: s, design-approved

#2846 pre-bold instead of develop as the exception branch used to check submodule pin for nitro-contracts
  .github/workflows/submodule-pin-check.yml
Labels: s, design-approved

#2844 [NIT-3006] fix: BlockValidator is added twice to LatestStakedNotifiers in pre-BOLD case
  staker/legacy/staker.go
Labels: s, design-approved

#2840 [NIT-2991] Get rid of receiver methods on aliased cgo types
  arbos/programs/native.go
  arbos/programs/testcompile.go
Labels: s, design-approved

#2827 stylus_benchmark
  .dockerignore
  .github/workflows/arbitrator-ci.yml
  arbitrator/Cargo.toml
  arbitrator/arbutil/src/benchmark.rs
  arbitrator/arbutil/src/lib.rs
  arbitrator/jit/src/lib.rs
  arbitrator/jit/src/main.rs
  arbitrator/jit/src/prepare.rs
  arbitrator/jit/src/program.rs
  arbitrator/jit/src/stylus_backend.rs
  arbitrator/stylus/src/env.rs
  arbitrator/stylus/src/host.rs
  arbitrator/stylus/src/native.rs
  arbitrator/tools/stylus_benchmark/Cargo.lock
  arbitrator/tools/stylus_benchmark/Cargo.toml
  arbitrator/tools/stylus_benchmark/src/benchmark.rs
  arbitrator/tools/stylus_benchmark/src/main.rs
  arbitrator/tools/stylus_benchmark/src/scenario.rs
  arbitrator/wasm-libraries/user-host-trait/src/lib.rs
  arbitrator/wasm-libraries/user-host/src/program.rs
  arbitrator/wasm-libraries/user-test/src/program.rs
Labels: s, design-approved

#2695 Add timeboosted information to broadcast feed
  arbnode/inbox_tracker.go
  arbnode/node.go
  arbnode/schema.go
  arbnode/transaction_streamer.go
  arbos/arbostypes/messagewithmeta.go
  broadcastclient/broadcastclient_test.go
  broadcaster/broadcaster.go
  broadcaster/broadcaster_test.go
  broadcaster/message/message.go
  broadcaster/message/message_blockmetadata_test.go
  broadcaster/message/message_serialization_test.go
  execution/gethexec/executionengine.go
  execution/gethexec/node.go
  execution/gethexec/sequencer.go
  execution/interface.go
  system_tests/timeboost_test.go
Labels: s

#2735 Publish Timeboost BlockMetadata to Sequencer Coordinator's redis
  arbnode/inbox_test.go
  arbnode/inbox_tracker.go
  arbnode/seq_coordinator.go
  arbnode/seq_coordinator_test.go
  arbnode/transaction_streamer.go
  system_tests/contract_tx_test.go
  system_tests/reorg_resequencing_test.go
  system_tests/seq_coordinator_test.go
  util/redisutil/redis_coordinator.go
Labels: s

#2854 Fall back to the confirmed state if the agreed state is nil.
  staker/bold/bold_staker.go
Labels: s, design-approved

#2796 Add flag to disable DAS chunked stores
  cmd/datool/datool.go
  das/aggregator.go
  das/aggregator_test.go
  das/dasRpcClient.go
  das/rpc_aggregator.go
  das/rpc_test.go
  system_tests/das_test.go
Labels: s, design-approved

#2850 Fix processing of transactions in expressLaneService
  execution/gethexec/express_lane_service.go
  execution/gethexec/express_lane_service_test.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
  timeboost/errors.go
Labels: s

#2542 [Config Change] Removes HardReorg config from InboxReader
  arbnode/delayed_seq_reorg_test.go
  arbnode/inbox_reader.go
  arbnode/inbox_tracker.go
  cmd/nitro/nitro.go
  system_tests/seqinbox_test.go
Labels: s, design-approved

#2859 wasmer: check against correct branch
  .github/workflows/submodule-pin-check.yml
Labels: s, design-approved
