Repository OffchainLabs/nitro, pull requests merged in 2025-02, with the labels that each got.

#2917 chainInfo supports track-block-metadata-from
  cmd/chaininfo/chain_info.go
  cmd/nitro/nitro.go
Labels: design-approved

#2918 Timeboost: Don't store or publish to feed, blockMetadata of blocks lower than TrackBlockMetadataFrom config option
  arbnode/transaction_streamer.go
Labels: design-approved

#2919 allow sequencer to collect metadata without timeboost
  cmd/nitro/nitro.go
Labels: design-approved

#2920 Add block-metadata to sepolia chain-info
  cmd/chaininfo/arbitrum_chain_info.json
Labels: design-approved

#2928 Mark `timeboost` as dangerous since it is a work in progress
  cmd/nitro/nitro.go
  execution/gethexec/express_lane_service.go
  execution/gethexec/node.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
Labels: design-approved

#2926 Fix reading of pending ExpressLane messages from redis
  execution/gethexec/express_lane_service.go
  execution/gethexec/express_lane_service_test.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
  timeboost/redis_coordinator.go
  timeboost/redis_coordinator_test.go
Labels: design-approved

#2931 remove block metadata from sepolia
  cmd/chaininfo/arbitrum_chain_info.json
Labels: design-approved

#2932 Allow BlockMetadata to be generated when timeboost isn't enabled
  arbnode/inbox_test.go
  execution/gethexec/executionengine.go
  execution/gethexec/node.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
  timeboost/redis_coordinator.go
Labels: design-approved

#2933 Update LICENSE.md
  LICENSE.md
Labels: Type: Documentation, Priority: P2 Low, design-approved

#2938 Start tracking metadata in sepolia
  cmd/chaininfo/arbitrum_chain_info.json
Labels: design-approved

#2942 update stake-token to WETH on L1 for 3.5.1 branch
  cmd/chaininfo/arbitrum_chain_info.json
Labels: design-approved

#2941 update stake-token to WETH on L1
  cmd/chaininfo/arbitrum_chain_info.json
Labels: design-approved

#2940 Update the pin check to expect the v2-main branch of nitro-contracts
  .github/workflows/submodule-pin-check.yml
Labels: design-approved

#2947 Backport fix syncMonitor's BlockMetadataByNumber response for arb classic block numbers
  execution/gethexec/sync_monitor.go
Labels: design-approved

#2939 Start tracking metadata in sepolia
  cmd/chaininfo/arbitrum_chain_info.json
Labels: design-approved

#2913 Creates new http client in BlobClient in case of request errors
  util/headerreader/blob_client.go
Labels: design-approved

#2952 fix submodule pin checks
  .github/workflows/submodule-pin-check.yml
Labels: design-approved

#2957 fix bold submodule pin checks
  .github/workflows/submodule-pin-check.yml
Labels: design-approved

#2935 [NIT-2977] Add TestFastConfirmationWithdrawal
  system_tests/fast_confirm_test.go
Labels: design-approved

#2945 Add trackers for missing block metadata retroactively
  arbnode/transaction_streamer.go
  arbnode/tx_streamer_test.go
Labels: design-approved

#2961 Hex encode bidder signatures in S3 published CSVs
  timeboost/db.go
  timeboost/db_test.go
  timeboost/s3_storage_test.go
Labels: design-approved

#2960 Hex encode bidder signatures in S3 published CSVs
  timeboost/db.go
  timeboost/db_test.go
  timeboost/s3_storage_test.go
Labels: design-approved

#2924 [NIT-3084] Check if the JSON-RPC error code is 3 for confirming execution reverted
  arbnode/delay_buffer.go
  cmd/nitro/nitro.go
  staker/legacy/l1_validator.go
  staker/multi_protocol/multi_protocol_staker.go
  staker/rollup_watcher.go
  util/headerreader/execution_reverted_test.go
  util/headerreader/header_reader.go
Labels: design-approved

#2676 Test flatCallTracer on Arbitrum blocks inside existing tests
  system_tests/retryable_test.go
Labels: s, design-approved

#2973 Create manifest buildspec
  .github/manifest-builspec.yml
Labels: design-approved

#2972 Remove cargo fmt check for rust from nitro repo
  .github/workflows/arbitrator-ci.yml
  Makefile
Labels: design-approved

#2971 Fix auction resolution during a tie
  system_tests/timeboost_test.go
  timeboost/auctioneer.go
  timeboost/bid_cache.go
  timeboost/types.go
Labels: design-approved
