Repository OffchainLabs/nitro, pull requests merged in 2025-04, with the labels that each got.

#3064 Correctly start and stop validation node
  cmd/nitro-val/nitro_val.go
  cmd/nitro/nitro.go
  system_tests/common_test.go
  validator/valnode/validation_api.go
  validator/valnode/valnode.go
Labels: design-approved

#2983 feat(arbitrator): NativeInstance::from_bytes
  arbitrator/stylus/src/native.rs
Labels: design-approved

#3019 stylus: record all writes on setTrieSlots
  arbos/programs/api.go
Labels: design-approved

#3072 Update the submodule-pin-check for `contracts` submodules
  .github/workflows/submodule-pin-check.yml
Labels: design-approved

#3076 fix pin submodule to develop
  .github/workflows/submodule-pin-check.yml
Labels: design-approved

#3077 deploy: fix typo
  cmd/deploy/deploy.go
Labels: design-approved

#2742 Improve precompile counting test
  precompiles/precompile_test.go
Labels: testing, design-approved

#3078 Set block to start tracking arb1 block metadata
  cmd/chaininfo/arbitrum_chain_info.json
Labels: design-approved

#3042 chore: fix license links in documentation
  LICENSE
  arbitrator/arbutil/src/benchmark.rs
  arbitrator/arbutil/src/crypto.rs
  arbitrator/arbutil/src/evm/storage.rs
  arbitrator/arbutil/src/math.rs
  arbitrator/arbutil/src/operator.rs
  arbitrator/brotli/fuzz/fuzz_targets/compress.rs
  arbitrator/brotli/fuzz/fuzz_targets/decompress.rs
  arbitrator/brotli/fuzz/fuzz_targets/round_trip.rs
  arbitrator/jit/src/arbcompress.rs
  arbitrator/jit/src/caller_env.rs
  arbitrator/jit/src/machine.rs
  arbitrator/jit/src/main.rs
  arbitrator/jit/src/prepare.rs
  arbitrator/jit/src/socket.rs
  arbitrator/jit/src/test.rs
  arbitrator/jit/src/wasip1_stub.rs
  arbitrator/jit/src/wavmio.rs
  arbitrator/prover/src/host.rs
  arbitrator/prover/src/memory.rs
  arbitrator/prover/src/merkle.rs
  arbitrator/prover/src/programs/counter.rs
  arbitrator/prover/src/programs/depth.rs
  arbitrator/prover/src/programs/meter.rs
  arbitrator/prover/src/programs/prelude.rs
  arbitrator/prover/src/programs/start.rs
  arbitrator/prover/src/reinterpret.rs
  arbitrator/prover/src/test.rs
  arbitrator/prover/src/utils.rs
  arbitrator/prover/src/value.rs
  arbitrator/stylus/src/benchmarks.rs
  arbitrator/stylus/src/env.rs
  arbitrator/stylus/src/host.rs
  arbitrator/stylus/src/run.rs
  arbitrator/stylus/src/test/wavm.rs
  arbitrator/wasm-libraries/arbcompress/build.rs
  arbitrator/wasm-libraries/arbcompress/src/lib.rs
  arbitrator/wasm-libraries/host-io/src/lib.rs
  arbitrator/wasm-libraries/user-host-trait/src/lib.rs
  arbitrator/wasm-libraries/user-host/src/host.rs
  arbitrator/wasm-libraries/user-test/src/host.rs
  arbitrator/wasm-libraries/wasi-stub/src/lib.rs
  arbitrator/wasm-testsuite/src/main.rs
Labels: design-approved

#3084 [Backport] Rectify evm depth modification while faking a call inside StartTxHook for arb type txs
  arbos/tx_processor.go
  system_tests/debugapi_test.go
Labels: design-approved

#2749 Add a nitro option to stop syncing at a given block number
  arbnode/delayed_sequencer.go
  arbnode/inbox_reader.go
  arbnode/inbox_test.go
  arbnode/seq_coordinator.go
  arbnode/transaction_streamer.go
  broadcastclient/broadcastclient.go
  broadcastclients/broadcastclients.go
  cmd/nitro/nitro.go
  execution/gethexec/executionengine.go
  execution/gethexec/node.go
  system_tests/bold_challenge_protocol_test.go
  system_tests/common_test.go
  util/stopwaiter/stopwaiter.go
Labels: s, design-approved

#3025 Adds TestOutOfGasInStorageCacheFlush
  arbitrator/stylus/tests/multicall/src/main.rs
  system_tests/program_gas_test.go
  system_tests/program_test.go
  system_tests/stylus_trace_test.go
  system_tests/stylus_tracer_test.go
Labels: design-approved

#3080 Rectify evm depth modification while faking a call inside StartTxHook for arb type txs
  arbos/tx_processor.go
  system_tests/debugapi_test.go
Labels: design-approved

#2802 Use flag instead of env var for system_test
  .github/workflows/ci.yml
  .github/workflows/gotestsum.sh
  .github/workflows/nightly-ci.yml
  Makefile
  arbos/programs/cgo_test.go
  das/aggregator_test.go
  system_tests/common_test.go
  system_tests/das_test.go
  system_tests/full_challenge_impl_test.go
  system_tests/recreatestate_rpc_test.go
  system_tests/staterecovery_test.go
  util/redisutil/test_redis.go
  util/testhelpers/env/env.go
  util/testhelpers/flag/flag.go
Labels: s, design-approved

#3089 Validate timeboost config options correctly and make timeboost config not dangerous
  cmd/nitro/nitro.go
  execution/gethexec/express_lane_service.go
  execution/gethexec/node.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
Labels: design-approved

#2885 feat: add sequencer dangerous flag to disable tx size checks
  cmd/nitro/nitro.go
  execution/gethexec/sequencer.go
Labels: design-approved

#3090 Validate timeboost config options correctly and make timeboost config not dangerous
  cmd/nitro/nitro.go
  execution/gethexec/express_lane_service.go
  execution/gethexec/node.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
Labels: design-approved

#3094 Fix Slack Notify on Nightly CI Failure With Correct Yaml Args
  .github/workflows/nightly-ci.yml
Labels: design-approved

#3083 Speedup timeboost systemTests
  arbnode/transaction_streamer.go
  system_tests/common_test.go
  system_tests/seq_coordinator_test.go
  system_tests/timeboost_test.go
Labels: design-approved

#3021 Improve enum mapping, and clarify hex decoding error in types.rs
  arbitrator/arbutil/src/types.rs
Labels: design-approved

#3097 Add support for consensus v40 to Docker
  Dockerfile
Labels: design-approved

#3098 Add a node.batch-poster.dangerous.fixed-gas-limit flag
  arbnode/batch_poster.go
Labels: design-approved

#3101 Add cargo fmt check for rust
  .github/workflows/arbitrator-ci.yml
  Makefile
  arbitrator/arbutil/src/evm/req.rs
  arbitrator/stylus/src/test/api.rs
Labels: design-approved

#3103 Use the new nolint directive
  arbnode/seq_coordinator.go
Labels: design-approved

#3104 Fix Broken Challenge Test CI
  system_tests/bold_challenge_protocol_test.go
Labels: design-approved

#3099 Add a node.batch-poster.dangerous.fixed-gas-limit flag
  arbnode/batch_poster.go
Labels: design-approved

#3106 Minor fix for timeboost system_tests
  system_tests/timeboost_test.go
Labels: design-approved

#3107 [Backport] Make some timeboost errors clearer
  timeboost/errors.go
Labels: design-approved

#3102 fix: Consistent bash imports in scripts (new PR for collaboration)
  scripts/build-brotli.sh
  scripts/check-build.sh
  scripts/remove_reference_types.sh
  scripts/split-val-entry.sh
Labels: design-approved

#3100 batch_poster: override delayed inbox for gas estimation
  arbnode/batch_poster.go
Labels: design-approved

#3113 Fix panic in sync-till-block option
  execution/gethexec/executionengine.go
Labels: design-approved

#3114 Fix race in TestTimeboostExpressLaneTransactionHandlingComplex
  system_tests/timeboost_test.go
Labels: design-approved

#3117 batch_poster: override delayed inbox pointer when sending future txs
  arbnode/batch_poster.go
Labels: design-approved

#3115 Fix path concatenation and GCS data write logic; improve cross-platform compatibility
  das/fallback_storage_service.go
  das/google_cloud_storage_service.go
  das/key_utils.go
Labels: design-approved

#3122 Simple block-recording test
  .github/workflows/ci.yml
  system_tests/block_validator_test.go
  util/testhelpers/flag/flag.go
Labels: design-approved

#3116 Test batch poster with delay proofs and backlog
  system_tests/batch_poster_test.go
  system_tests/client_wrapper.go
  system_tests/common_test.go
Labels: design-approved

#3119 Implement detailed retryable comparison in initialization tests
  arbos/arbosState/initialization_test.go
Labels: design-approved

#3135 Fix Broken Challenge Tests on Master
  system_tests/bold_state_provider_test.go
  system_tests/overflow_assertions_test.go
Labels: design-approved

#3126 Cleanup github actions
  .github/workflows/arbitrator-ci.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/nightly-ci.yml
Labels: design-approved

#3136 Fix Challenge Test Failures due to Improper Resource Cleanup
  system_tests/bold_challenge_protocol_test.go
  system_tests/bold_l3_support_test.go
Labels: design-approved

#3139 Lint cleanup
  wsbroadcastserver/clientconnection.go
Labels: design-approved

#3051 Handle reorg issues when setting finality data in Execution
  arbnode/consensus_execution_syncer.go
  arbnode/inbox_test.go
  arbnode/node.go
  arbutil/finality_data.go
  execution/gethexec/executionengine.go
  execution/gethexec/node.go
  execution/gethexec/sync_monitor.go
  execution/interface.go
  system_tests/ancients_finalized_test.go
  system_tests/finality_data_test.go
Labels: design-approved

#3141 Avoid CI cache key collision
  .github/workflows/arbitrator-ci.yml
  .github/workflows/codeql-analysis.yml
Labels: design-approved

#3142 Move Challenge Tests to Nightly Ensuring They Still Build in Each PR
  .github/workflows/ci.yml
  .github/workflows/nightly-ci.yml
Labels: design-approved

#3149 Check chainid before starting BlockMetadataFetcher
  arbnode/blockmetadata.go
  arbnode/node.go
  system_tests/timeboost_test.go
Labels: design-approved

#3152 Use Error Log Levels in Tests, Introduce L3 Challenge Workflow
  .github/workflows/gotestsum.sh
  .github/workflows/nightly-ci.yml
  system_tests/bold_l3_support_test.go
Labels: design-approved

#3155 enable TestL3ChallengeProtocolBOLD
  system_tests/bold_l3_support_test.go
Labels: design-approved

#3150 Log an error when unable to forward transaction to any of the targets
  execution/gethexec/forwarder.go
Labels: design-approved

#3166 Get Bold L3 Test Passing
  .github/workflows/ci.yml
  system_tests/bold_challenge_protocol_test.go
  system_tests/bold_l3_support_test.go
Labels: design-approved

#3164 Additional documentation for usage of StateDB object in preTxFilters
  arbos/block_processor.go
  arbos/extra_transaction_checks.go
Labels: design-approved

#3161 Auction resolution tx should not be considered as timeboosted
  execution/gethexec/sequencer.go
Labels: design-approved

#3151 Feed disconnect error should be logged at level error if it happens more than once per minute
  broadcastclient/broadcastclient.go
Labels: design-approved

#3168 ExpressLane txs erroring due to context timing out at the end of a round shouldn't be logged as an error
  execution/gethexec/express_lane_service.go
Labels: design-approved

#3154 Reduce the Noise of Sequencer Coordinator Logging
  util/redisutil/redis_coordinator.go
Labels: design-approved

#3145 Enable TestSequencerInboxReader system test
  system_tests/seqinbox_test.go
Labels: design-approved

#3169 Add support for consensus v40 to Docker
  Dockerfile
Labels: design-approved

#3160 Cleanup github actions
  .github/workflows/arbitrator-ci.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/nightly-ci.yml
Labels: design-approved

#3172 Comparing two gas estimations must be on same block
  arbnode/batch_poster.go
Labels: design-approved

#3177 Fix timeboost signature checking
  timeboost/bid_validator.go
  timeboost/bid_validator_test.go
Labels: design-approved

#3131 Enable blockmetadata syncing by default for arb1/nova
  arbnode/blockmetadata.go
  arbnode/transaction_streamer.go
  cmd/chaininfo/arbitrum_chain_info.json
  cmd/chaininfo/chain_info.go
  cmd/nitro/nitro.go
Labels: design-approved

#3178 Re-execute execution reverted for eth_estimateGas as eth_call for better logs in batch poster
  arbnode/batch_poster.go
Labels: design-approved

#3180 sync_monitor: not synced when starting up
  arbnode/seq_coordinator.go
  arbnode/sync_monitor.go
  execution/gethexec/sync_monitor.go
  system_tests/seq_coordinator_test.go
Labels: design-approved

#3182 delay buffer always updateable
  arbnode/batch_poster.go
Labels: design-approved

#3181 ci: Update GitHub Actions cache from v3 to v4
  .github/workflows/arbitrator-ci.yml
  .github/workflows/ci.yml
Labels: design-approved

#3188 Set non zero GasMargin for auction resolution tx and enabling retrying with a new tx upon failure
  timeboost/auctioneer.go
Labels: design-approved
