Repository OffchainLabs/nitro, pull requests merged in 2025-01, with the labels that each got.

#2296 [NIT-2484] snap-sync consensus 0.2: start reading parent chain from the right block
  arbnode/node.go
Labels: s, design-approved

#2852 Add metrics for how many Stylus calls and gas used
  arbos/programs/programs.go
Labels: s, design-approved

#2864 remove most occurences of log.Crit
  arbos/arbosState/arbosstate.go
  arbos/arbosState/initialize.go
  arbos/programs/api.go
  arbos/programs/native_api.go
  arbos/programs/programs.go
  arbstate/inbox.go
  precompiles/context.go
  precompiles/precompile.go
  precompiles/precompile_test.go
  system_tests/staker_test.go
Labels: s, design-approved

#2838 [NIT-2987] Store last message pruned in database
  arbnode/message_pruner.go
  arbnode/schema.go
Labels: s, design-approved

#2860 [config change] Improve timeboost implementation
  cmd/nitro/nitro.go
  execution/gethexec/contract_adapter.go
  execution/gethexec/express_lane_service.go
  execution/gethexec/express_lane_service_test.go
  execution/gethexec/node.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
  timeboost/types.go
Labels: s

#2739 On-demand module compile
  arbos/programs/native.go
  arbos/programs/programs.go
  arbos/programs/wasmstorehelper.go
  execution/gethexec/node.go
  system_tests/common_test.go
  system_tests/program_test.go
Labels: s, design-approved

#2872 fix arbitrator-ci
  .github/workflows/arbitrator-ci.yml
Labels: s, design-approved

#2871 Create a metric for local block execution time
  execution/gethexec/executionengine.go
Labels: s, design-approved

#2812 Create ADR-0001 Avoid primative constraint types
  docs/decisions/0000-use-markdown-architectural-decision-records.md
  docs/decisions/0001-avoid-primitive-constraint-types.md
  docs/decisions/README.md
  docs/decisions/adr-template-bare-minimal.md
  docs/decisions/adr-template-bare.md
  docs/decisions/adr-template-minimal.md
  docs/decisions/adr-template.md
Labels: s, design-approved

#2794 feat: update google-cloud-storage parameters and object retention setting
  das/google_cloud_storage_service.go
  das/google_cloud_storage_service_test.go
Labels: s, design-approved

#2877 Enable the geth trie prefetcher for the sequencer
  execution/gethexec/executionengine.go
Labels: s, design-approved

#2875 refactor: using slices.Contains to simplify the code
  cmd/conf/init.go
Labels: design-approved

#2810 chore: fix some problematic method name and typos in comment
  cmd/datool/datool.go
  execution/nodeInterface/NodeInterface.go
  relay/relay_stress_test.go
  system_tests/outbox_test.go
  system_tests/seqinbox_test.go
Labels: design-approved

#2842 [NIT-2799] Add mock external signer binary
  Dockerfile
  Makefile
  arbnode/dataposter/data_poster.go
  arbnode/dataposter/dataposter_test.go
  arbnode/dataposter/externalsignertest/externalsignertest.go
  cmd/mockexternalsigner/mockexternalsigner.go
  system_tests/batch_poster_test.go
  system_tests/fast_confirm_test.go
  system_tests/staker_test.go
Labels: s, design-approved

#2634 chore: fix typos in `validator/server_jit/spawner.go`
  validator/server_jit/spawner.go
Labels: s, design-approved

#2884 Upgrade actions/upload-artifact in CI
  .github/workflows/ci.yml
  .github/workflows/docker.yml
Labels: design-approved

#2888 Add the installation of the cbindgen binary
  .github/workflows/codeql-analysis.yml
Labels: design-approved

#2799 add retryable expiry system tests
  system_tests/retryable_test.go
Labels: s, design-approved

#2886 chore: fix some function names in comment
  arbnode/batch_poster.go
  arbnode/delay_buffer.go
  cmd/genericconf/logging.go
Labels: design-approved

#2870 More benchmarks in stylus_benchmark
  .github/workflows/arbitrator-ci.yml
  arbitrator/jit/src/program.rs
  arbitrator/tools/stylus_benchmark/Cargo.lock
  arbitrator/tools/stylus_benchmark/Cargo.toml
  arbitrator/tools/stylus_benchmark/src/benchmark.rs
  arbitrator/tools/stylus_benchmark/src/main.rs
  arbitrator/tools/stylus_benchmark/src/scenario.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/br.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/br_if.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/br_table.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/call.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/call_indirect.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/convert.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/data_type.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/global_get.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/global_set.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/if_op.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/instruction_with_1_arg_1_return.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/instruction_with_2_args_1_return.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/load.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/local_get.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/local_set.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/local_tee.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/mod.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/select.rs
  arbitrator/tools/stylus_benchmark/src/scenarios/store.rs
Labels: s, design-approved

#2905 Attempt to Reduce Flakiness of BoLD Virtual Block System Tests
  staker/bold/bold_state_provider.go
  system_tests/bold_new_challenge_test.go
Labels: design-approved

#2897 maintenance api
  arbnode/api.go
  arbnode/maintenance.go
  arbnode/node.go
Labels: design-approved

#2903 Express lane timeboost auctioneer rpc forwarding and sequencer coordinator
  execution/gethexec/forwarder.go
  execution/gethexec/node.go
  execution/gethexec/sequencer.go
  system_tests/timeboost_test.go
  timeboost/auctioneer.go
  timeboost/sequencer_endpoint_manager.go
Labels: design-approved
